//MIT License
//
//Copyright (c) 2017-2018 SENSORMATIC ELECTRONICS LLC, NATHAN E NELSON
//
//Permission is hereby granted, free of charge, to any person obtaining a copy
//of this software and associated documentation files (the "Software"), to deal
//in the Software without restriction, including without limitation the rights
//to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//copies of the Software, and to permit persons to whom the Software is
//furnished to do so, subject to the following conditions:
//
//The above copyright notice and this permission notice shall be included in all
//copies or substantial portions of the Software.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//SOFTWARE.

function StyleListRenderer(){StyleListRenderer.base.prototype.constructor.call(this);this.setStyle("LayoutGap",4);this.setStyle("PercentWidth",100);this._dropdownAdd=new DropdownElement;this._dropdownAdd.setStyle("PercentWidth",100);this._dropdownAdd.setStyle("ItemLabelFunction",StyleListRenderer.addStyleDropdownLabelFunction);this._dropdownAdd.setStyleDefinitions(addStyleDropdownStyle);this.addElement(this._dropdownAdd);var a=this;this._onLocaleChangedInstance=function(b){a._onLocaleChanged(b)};
this._onDropdownAddListItemClickInstance=function(b){a._onDropdownAddListItemClick(b)};this._onItemRendererClearedInstance=function(b){a._onItemRendererCleared(b)};this.addEventListener("localechanged",this._onLocaleChangedInstance);this._dropdownAdd.addEventListener("listitemclick",this._onDropdownAddListItemClickInstance);this._styleControlType=null}StyleListRenderer.prototype=Object.create(ListContainerElement.prototype);StyleListRenderer.prototype.constructor=StyleListRenderer;
StyleListRenderer.base=ListContainerElement;StyleListRenderer.addStyleDropdownLabelFunction=function(a){return""!=a.styleName?a.styleName:a.category};StyleListRenderer.prototype._onLocaleChanged=function(a){null!=this.getManager()&&null!=this._styleControlType&&(a=this.getManager().getLocale(),a=localeStrings[a].Add+" "+this._styleControlType.styleName,a.indexOf("Style")!=a.length-5&&(a+="Style"),this._dropdownAdd.setStyle("Text",a))};
StyleListRenderer.prototype._onDropdownAddListItemClick=function(a){a=a.getItem();if(""!=a.styleName){var b;if(a.styleName in a.styleDefinition._styleMap)for(var c=1;c<this.getNumElements();c++){if(b=this.getElementAt(c),b._styleControlType==a){this._clearItemRenderer(b);break}}else b=new StyleItemRenderer,b.addEventListener("cleared",this._onItemRendererClearedInstance),b.setStyleControlType(a),this.addElementAt(b,1),this._styleControlType.styleList.indexUpdated(this._styleControlType.styleList.getItemIndex(a)),
this.getManager().dispatchEvent(new DispatcherEvent("stylingchanged"))}};StyleListRenderer.prototype._onItemRendererCleared=function(a){this._clearItemRenderer(a.getTarget())};StyleListRenderer.prototype._clearItemRenderer=function(a){var b=a._styleControlType;b.styleDefinition.clearStyle(b.styleName);b.styleListCodeString="";b.styleItemCodeString="";this._styleControlType.styleList.indexUpdated(this._styleControlType.styleList.getItemIndex(b));this.removeElement(a);this.getManager().dispatchEvent(new DispatcherEvent("stylingchanged"))};
StyleListRenderer.prototype.setStyleControlType=function(a){this._styleControlType=a;for(this._onLocaleChanged(null);1<this.getNumElements();)this.getElementAt(1).removeEventListener("cleared",this._onItemRendererClearedInstance),this.removeElementAt(1);this._dropdownAdd.setListCollection(a.styleList);for(var b,c=0;c<a.styleList.getLength();c++)if(b=a.styleList.getItemAt(c),""!=b.styleName&&b.styleName in b.styleDefinition._styleMap){var d=new StyleItemRenderer;d.addEventListener("cleared",this._onItemRendererClearedInstance);
d.setStyleControlType(b);this.addElementAt(d,1)}};
function StyleItemRenderer(){StyleItemRenderer.base.prototype.constructor.call(this);this.setStyle("PercentWidth",100);this.setStyle("LayoutGap",4);this.setStyle("LayoutDirection","vertical");this._styleSelectBox=new ListContainerElement;this._styleSelectBox.setStyle("LayoutDirection","horizontal");this._styleSelectBox.setStyle("LayoutVerticalAlign","middle");this._styleSelectBox.setStyle("LayoutGap",4);this._styleSelectBox.setStyle("PercentWidth",100);this._styleSelectBox.setStyle("MinHeight",18);
this._labelStyleName=new LabelElement;this._labelStyleName.setStyle("PercentWidth",100);this._labelStyleName.setStyle("PaddingRight",20);this._buttonClearStyle=new ButtonElement;this._buttonClearStyle.setStyleDefinitions(clearStyleButtonStyle);this._styleChangeControl=this._styleNullCheckbox=null;this._styleSelectBox.addElement(this._labelStyleName);this._styleSelectBox.addElement(this._buttonClearStyle);this.addElement(this._styleSelectBox);this._styleListRenderer=null;var a=this;this._onValueChangedInstance=
function(b){a._onValueChanged(b)};this._onButtonClearStyleClickInstance=function(b){a._onButtonClearStyleClick(b)};this._onNullCheckboxChangedInstance=function(b){a._onNullCheckboxChanged(b)};this._buttonClearStyle.addEventListener("click",this._onButtonClearStyleClickInstance);this._styleControlType=null}StyleItemRenderer.prototype=Object.create(ListContainerElement.prototype);StyleItemRenderer.prototype.constructor=StyleItemRenderer;StyleItemRenderer.base=ListContainerElement;
StyleItemRenderer.prototype.setStyleControlType=function(a){this._styleControlType=a;for(this._labelStyleName.setStyle("Text",a.styleName);2<this._styleSelectBox.getNumElements();)this._styleSelectBox.removeElementAt(1);var b=void 0;a.styleName in a.styleDefinition._styleMap&&(b=a.styleDefinition._styleMap[a.styleName]);void 0===b?b=1==a.allowNull&&1==a.initNull?null:a.initValue:b instanceof StyleDefinition&&(b=Object.getPrototypeOf(b).constructor);if(null==a.allowValues)this._styleChangeControl=
new TextInputElement,null==b?this._styleChangeControl.setText(a.initValue):this._styleChangeControl.setText(b.toString()),this._styleChangeControl.addEventListener("changed",this._onValueChangedInstance);else if(1==a.allowValues.length)this._styleChangeControl=new LabelElement,this._styleChangeControl.setStyle("Text",a.allowValues[0].label);else{this._styleChangeControl=new DropdownElement;this._styleChangeControl.setListCollection(new ListCollection(a.allowValues));for(var c=-1,d=0;d<a.allowValues.length;d++)if(null!=
b&&b==a.allowValues[d].value||null==b&&a.initValue==a.allowValues[d].value){c=d;break}-1!=c?this._styleChangeControl.setSelectedIndex(c):this._styleChangeControl.setSelectedIndex(0);this._styleChangeControl.addEventListener("changed",this._onValueChangedInstance)}1==a.allowNull&&(this._styleNullCheckbox=new CheckboxElement,this._styleNullCheckbox.setStyle("Text","null"),this._styleNullCheckbox.setStyle("PaddingRight",15),this._styleNullCheckbox.addEventListener("changed",this._onNullCheckboxChangedInstance),
null==b&&this._styleNullCheckbox.setSelected(!0),this._styleSelectBox.addElementAt(this._styleNullCheckbox,this._styleSelectBox.getNumElements()-1));this._styleChangeControl.setStyle("Width",150);this._styleSelectBox.addElementAt(this._styleChangeControl,this._styleSelectBox.getNumElements()-1);this._onNullCheckboxChanged(null)};StyleItemRenderer.prototype._onButtonClearStyleClick=function(a){this.dispatchEvent(new DispatcherEvent("cleared"))};
StyleItemRenderer.prototype._onNullCheckboxChanged=function(a){null!=this._styleNullCheckbox&&1==this._styleNullCheckbox.getSelected()?(this._updateStyleValue(null),this._styleChangeControl.setStyle("Enabled",!1)):(this._onValueChanged(null),this._styleChangeControl.setStyle("Enabled",!0))};
StyleItemRenderer.prototype._onValueChanged=function(a){a=null!=this._styleControlType.allowValues&&1==this._styleControlType.allowValues.length?this._styleControlType.allowValues[0].value:this._styleChangeControl instanceof TextInputElement?this._styleChangeControl.getText():this._styleChangeControl.getSelectedItem().value;this._updateStyleValue(a)};
StyleItemRenderer.prototype._updateStyleValue=function(a){for(var b="",c=this._styleControlType.parent;null!=c;)b=c.styleName+b,c=c.parent;for(var d=b.indexOf("Style");-1!=d&&d!=b.length-5;)b=b.substring(0,d)+b.substring(d+5),d=b.indexOf("Style");this._styleControlType.styleListCodeString="";this._styleControlType.styleItemCodeString=b+'.setStyle("'+this._styleControlType.styleName+'", ';c=!1;if(null!=a)if("number"==this._styleControlType.styleType)a=Number(a),this._styleControlType.styleItemCodeString+=
a+");";else if("class"==this._styleControlType.styleType){b+=this._styleControlType.styleName;for(d=b.indexOf("Style");-1!=d&&d!=b.length-5;)b=b.substring(0,d)+b.substring(d+5),d=b.indexOf("Style");this._styleControlType.styleListCodeString="var "+b+" = new "+a.toString().match(/function ([A-Z]{1}[a-zA-Z]*)/)[1]+"();\r\n";this._styleControlType.styleItemCodeString+=b+");";b=void 0;this._styleControlType.styleName in this._styleControlType.styleDefinition._styleMap&&(b=this._styleControlType.styleDefinition._styleMap[this._styleControlType.styleName]);
a=b instanceof a?b:new a}else if("bool"==this._styleControlType.styleType)this._styleControlType.styleItemCodeString=1==a?this._styleControlType.styleItemCodeString+"true);":this._styleControlType.styleItemCodeString+"false);";else if("json"==this._styleControlType.styleType){this._styleControlType.styleItemCodeString+=a+");";try{a=JSON.parse(a)}catch(e){c=!0}}else a=a.toString(),this._styleControlType.styleItemCodeString+='"'+a+'");';else this._styleControlType.styleItemCodeString+="null);";this._styleControlType.styleItemCodeString+=
"\r\n";0==c&&this._styleControlType.styleDefinition.setStyle(this._styleControlType.styleName,a);a instanceof StyleDefinition?(this._styleControlType.buildControlStyleTypeLists(),0<this._styleControlType.styleList.getLength()?(this._labelStyleName.setStyle("TextStyle","bold"),null==this._styleListRenderer&&(this._styleListRenderer=new StyleListRenderer,this._styleListRenderer.setStyle("PaddingLeft",30),this.addElement(this._styleListRenderer)),this._styleListRenderer.setStyleControlType(this._styleControlType)):
(this._labelStyleName.setStyle("TextStyle","normal"),null!=this._styleListRenderer&&(this.removeElement(this._styleListRenderer),this._styleListRenderer=null))):(this._labelStyleName.setStyle("TextStyle","normal"),null!=this._styleListRenderer&&(this.removeElement(this._styleListRenderer),this._styleListRenderer=null));null!=this.getManager()&&this.getManager().dispatchEvent(new DispatcherEvent("stylingchanged"))};var localeStrings=Object.create(null);localeStrings.all=Object.create(null);
localeStrings.all.FlexCanvasJS="FlexCanvasJS";localeStrings.all["Style Explorer"]="Style Explorer";localeStrings["en-us"]=Object.create(null);localeStrings["en-us"].Language="Language";localeStrings["en-us"]["Powered By"]="Powered By";localeStrings["en-us"]["Select Control"]="Select Control";localeStrings["en-us"]["Select Styles"]="Select Styles";localeStrings["en-us"].Sandbox="Sandbox";localeStrings["en-us"].Add="Add";localeStrings["en-us"].Styles="Styles";localeStrings["en-us"]["Style Code"]="Style Code";
localeStrings["en-us"].Copy="Copy";localeStrings["en-us"]["Text Size"]="Text Size";localeStrings["en-us"]["Press Ctrl C"]="Press CTRL + C";localeStrings["es-es"]=Object.create(null);localeStrings["es-es"].Language="Idioma";localeStrings["es-es"]["Powered By"]="Desarrollado Por";localeStrings["es-es"]["Select Control"]="Seleccionar Control";localeStrings["es-es"]["Select Styles"]="Seleccionar Estilos";localeStrings["es-es"].Sandbox="Salvadera";localeStrings["es-es"].Add="A\u00f1adir";
localeStrings["es-es"].Styles="Estilos";localeStrings["es-es"]["Style Code"]="C\u00f3digo De Estilo";localeStrings["es-es"].Copy="Copiar";localeStrings["es-es"]["Text Size"]="Tamano Del Texto";localeStrings["es-es"]["Press Ctrl C"]="Presione CTRL + C";var urlImgBlueMarble="BlueMarble.jpg",canvasManagerStyle=new StyleDefinition;canvasManagerStyle.setStyle("BackgroundFill","#D9C7A6");var applicationContainerStyle=new StyleDefinition;applicationContainerStyle.setStyle("PaddingTop",4);
applicationContainerStyle.setStyle("PaddingLeft",4);applicationContainerStyle.setStyle("PaddingRight",4);applicationContainerStyle.setStyle("PaddingBottom",2);applicationContainerStyle.setStyle("LayoutGap",6);applicationContainerStyle.setStyle("MinHeight",500);var textTitleStyle=new StyleDefinition;textTitleStyle.setStyle("TextSize",32);textTitleStyle.setStyle("TextFont","Roboto");var panelBackgroundShape=new RoundedRectangleShape;panelBackgroundShape.setStyle("CornerRadius",6);
var panelBackgroundStyle=new StyleDefinition;panelBackgroundStyle.setStyle("BackgroundFill","#FFFFFF");panelBackgroundStyle.setStyle("BackgroundShape",panelBackgroundShape);panelBackgroundStyle.setStyle("Alpha",.35);panelBackgroundStyle.setStyle("PercentWidth",100);panelBackgroundStyle.setStyle("PercentHeight",100);var panelInnerContainerStyle=new StyleDefinition;panelInnerContainerStyle.setStyle("Padding",6);panelInnerContainerStyle.setStyle("PercentWidth",100);
panelInnerContainerStyle.setStyle("PercentHeight",100);var hDividerLineStyle=new StyleDefinition;hDividerLineStyle.setStyle("Height",1);hDividerLineStyle.setStyle("PercentWidth",100);hDividerLineStyle.setStyle("BackgroundFill","#999999");var clearStyleButtonStyle=new StyleDefinition,clearStyleButtonUpSkinStyleDef=new StyleDefinition;clearStyleButtonUpSkinStyleDef.setStyle("BackgroundFill","#FF7777");var clearStyleButtonOverSkinStyleDef=new StyleDefinition;
clearStyleButtonOverSkinStyleDef.setStyle("BackgroundFill","#EE5555");var clearStyleButtonDownSkinStyleDef=new StyleDefinition;clearStyleButtonDownSkinStyleDef.setStyle("BackgroundFill","#DD3333");clearStyleButtonStyle.setStyle("UpSkinStyle",clearStyleButtonUpSkinStyleDef);clearStyleButtonStyle.setStyle("OverSkinStyle",clearStyleButtonOverSkinStyleDef);clearStyleButtonStyle.setStyle("DownSkinStyle",clearStyleButtonDownSkinStyleDef);clearStyleButtonStyle.setStyle("SkinClass",CloseButtonSkinElement);
clearStyleButtonStyle.setStyle("Width",15);clearStyleButtonStyle.setStyle("Height",15);clearStyleButtonStyle.setStyle("BackgroundShape",new EllipseShape);var addStyleDropdownListStyle=new StyleDefinition;addStyleDropdownListStyle.setStyle("ListItemClass",AddStyleDataRenderer);addStyleDropdownListStyle.setStyle("Selectable",!1);var addStyleDropdownStyle=new StyleDefinition;addStyleDropdownStyle.setStyle("PopupDataListStyle",addStyleDropdownListStyle);var fontSizeButtonStyle=new StyleDefinition;
fontSizeButtonStyle.setStyle("SkinClass",ScrollButtonSkinElement);fontSizeButtonStyle.setStyle("Width",14);fontSizeButtonStyle.setStyle("PercentHeight",100);var stylesControlViewportVScrollbarStyle=new StyleDefinition;stylesControlViewportVScrollbarStyle.setStyle("PaddingLeft",4);var stylesControlViewportStyle=new StyleDefinition;stylesControlViewportStyle.setStyle("VerticalScrollBarStyle",stylesControlViewportVScrollbarStyle);stylesControlViewportStyle.setStyle("MinWidth",450);
stylesControlViewportStyle.setStyle("MeasureContentWidth",!0);var styleExplorer=null;function init(){styleExplorer=new StyleExplorerApplication;styleExplorer.setCanvas(document.getElementById("canvasStyleExplorer"))}
function StyleExplorerApplication(){StyleExplorerApplication.base.prototype.constructor.call(this);this.setStyleDefinitions(canvasManagerStyle);this.setStyle("TextSize",12);this._applicationViewport=new ViewportElement;this._applicationViewport.setStyle("PercentWidth",100);this._applicationViewport.setStyle("PercentHeight",100);this._applicationContainer=new ListContainerElement;this._applicationContainer.setStyle("LayoutDirection","vertical");this._applicationContainer.addStyleDefinition(applicationContainerStyle);
this._headerContainer=new ListContainerElement;this._headerContainer.setStyle("PercentWidth",100);this._headerContainer.setStyle("LayoutDirection","horizontal");this._textTitle=new TextElement;this._textTitle.setStyle("PercentWidth",100);this._textTitle.addStyleDefinition(textTitleStyle);this._settingsSelectContainer=new ListContainerElement;this._settingsSelectContainer.setStyle("LayoutDirection","horizontal");this._settingsSelectContainer.setStyle("LayoutVerticalAlign","middle");this._settingsSelectContainer.setStyle("LayoutGap",
2);this._labelLanguage=new LabelElement;this._labelLanguage.setStyle("PaddingLeft",20);this._dropdownLocale=new DropdownElement;this._labelFontSize=new LabelElement;this._labelFontSize.setStyle("PaddingLeft",20);this._buttonFontSmaller=new ButtonElement;this._buttonFontSmaller.setStyleDefinitions(fontSizeButtonStyle);this._buttonFontSmaller.setStyle("ArrowDirection","down");this._buttonFontSmaller.setStyle("Enabled",!1);this._buttonFontLarger=new ButtonElement;this._buttonFontLarger.setStyleDefinitions(fontSizeButtonStyle);
this._buttonFontLarger.setStyle("ArrowDirection","up");this._settingsSelectContainer.addElement(this._labelLanguage);this._settingsSelectContainer.addElement(this._dropdownLocale);this._settingsSelectContainer.addElement(this._labelFontSize);this._settingsSelectContainer.addElement(this._buttonFontSmaller);this._settingsSelectContainer.addElement(this._buttonFontLarger);this._headerContainer.addElement(this._textTitle);this._headerContainer.addElement(this._settingsSelectContainer);this._dividerHeader=
new CanvasElement;this._dividerHeader.setStyleDefinitions(hDividerLineStyle);this._contentContainer=new ListContainerElement;this._contentContainer.setStyle("PercentWidth",100);this._contentContainer.setStyle("PercentHeight",100);this._contentContainer.setStyle("LayoutDirection","horizontal");this._contentContainer.setStyle("LayoutGap",8);this._controlSelectOuterContainer=new AnchorContainerElement;this._controlSelectOuterContainer.setStyle("PercentHeight",100);this._controlSelectOuterContainer.setStyle("Width",
180);this._controlSelectPanelBackground=new CanvasElement;this._controlSelectPanelBackground.setStyleDefinitions(panelBackgroundStyle);this._controlSelectInnerContainer=new ListContainerElement;this._controlSelectInnerContainer.setStyleDefinitions(panelInnerContainerStyle);this._labelSelectControl=new LabelElement;this._labelSelectControl.setStyle("TextStyle","bold");this._dividerSelectControl=new CanvasElement;this._dividerSelectControl.setStyleDefinitions(hDividerLineStyle);this._spacerSelectControl=
new CanvasElement;this._spacerSelectControl.setStyle("PercentWidth",100);this._spacerSelectControl.setStyle("Height",5);this._dataListControls=new DataListElement;this._dataListControls.setStyle("PercentWidth",100);this._dataListControls.setStyle("PercentHeight",100);this._controlSelectInnerContainer.addElement(this._labelSelectControl);this._controlSelectInnerContainer.addElement(this._dividerSelectControl);this._controlSelectInnerContainer.addElement(this._spacerSelectControl);this._controlSelectInnerContainer.addElement(this._dataListControls);
this._controlSelectOuterContainer.addElement(this._controlSelectPanelBackground);this._controlSelectOuterContainer.addElement(this._controlSelectInnerContainer);this._styleSelectOuterContainer=new AnchorContainerElement;this._styleSelectOuterContainer.setStyle("PercentHeight",100);this._styleSelectPanelBackground=new CanvasElement;this._styleSelectPanelBackground.setStyleDefinitions(panelBackgroundStyle);this._styleSelectInnerContainer=new ListContainerElement;this._styleSelectInnerContainer.setStyleDefinitions(panelInnerContainerStyle);
this._labelSelectStyle=new LabelElement;this._labelSelectStyle.setStyle("TextStyle","bold");this._dividerSelectStyle=new CanvasElement;this._dividerSelectStyle.setStyleDefinitions(hDividerLineStyle);this._spacerSelectStyle=new CanvasElement;this._spacerSelectStyle.setStyle("PercentWidth",100);this._spacerSelectStyle.setStyle("Height",5);this._stylesControlViewport=new ViewportElement;this._stylesControlViewport.setStyle("PercentWidth",100);this._stylesControlViewport.setStyle("PercentHeight",100);
this._stylesControlViewport.setStyleDefinitions(stylesControlViewportStyle);this._stylesControlContainer=new ListContainerElement;this._stylesControlViewport.setElement(this._stylesControlContainer);this._styleSelectInnerContainer.addElement(this._labelSelectStyle);this._styleSelectInnerContainer.addElement(this._dividerSelectStyle);this._styleSelectInnerContainer.addElement(this._spacerSelectStyle);this._styleSelectInnerContainer.addElement(this._stylesControlViewport);this._styleSelectOuterContainer.addElement(this._styleSelectPanelBackground);
this._styleSelectOuterContainer.addElement(this._styleSelectInnerContainer);this._sandboxOuterContainer=new AnchorContainerElement;this._sandboxOuterContainer.setStyle("PercentHeight",100);this._sandboxOuterContainer.setStyle("PercentWidth",100);this._sandboxOuterContainer.setStyle("MinWidth",300);this._sandboxPanelBackground=new CanvasElement;this._sandboxPanelBackground.setStyleDefinitions(panelBackgroundStyle);this._sandboxInnerContainer=new ListContainerElement;this._sandboxInnerContainer.setStyleDefinitions(panelInnerContainerStyle);
this._sandboxHeaderContainer=new ListContainerElement;this._sandboxHeaderContainer.setStyle("PercentWidth",100);this._sandboxHeaderContainer.setStyle("LayoutDirection","horizontal");this._sandboxHeaderContainer.setStyle("LayoutVerticalAlign","middle");this._sandboxHeaderRadioButtonContainer=new ListContainerElement;this._sandboxHeaderRadioButtonContainer.setStyle("Padding",2);this._sandboxHeaderRadioButtonContainer.setStyle("LayoutGap",15);this._sandboxHeaderRadioButtonContainer.setStyle("LayoutVerticalAlign",
"middle");this._sandboxHeaderRadioButtonContainer.setStyle("LayoutDirection","horizontal");this._radioButtonSandbox=new RadioButtonElement;this._radioButtonSandbox.setStyle("TextStyle","bold");this._radioButtonStyleCode=new RadioButtonElement;this._radioButtonStyleCode.setStyle("TextStyle","bold");this._sandboxHeaderRadioButtonContainer.addElement(this._radioButtonSandbox);this._sandboxHeaderRadioButtonContainer.addElement(this._radioButtonStyleCode);this._sandboxHeaderContainer.addElement(this._sandboxHeaderRadioButtonContainer);
this._dividerSandbox=new CanvasElement;this._dividerSandbox.setStyleDefinitions(hDividerLineStyle);this._sandboxControlOuterContainer=new ListContainerElement;this._sandboxControlOuterContainer.setStyle("PercentWidth",100);this._sandboxControlOuterContainer.setStyle("PercentHeight",100);this._sandboxControlAndCodeContainer=new AnchorContainerElement;this._sandboxControlAndCodeContainer.setStyle("PercentWidth",100);this._sandboxControlAndCodeContainer.setStyle("PercentHeight",100);this._sandboxControlPanelBackground=
new CanvasElement;this._sandboxControlPanelBackground.setStyle("Top",5);this._sandboxControlPanelBackground.setStyle("Bottom",5);this._sandboxControlPanelBackground.setStyle("Left",5);this._sandboxControlPanelBackground.setStyle("Right",5);this._sandboxControlPanelBackground.setStyle("BackgroundFill","#FFFFFF");this._sandboxControlPanelBackground.setStyle("Alpha",.35);this._sandboxControlContainer=new AnchorContainerElement;this._sandboxControlContainer.setStyle("Top",5);this._sandboxControlContainer.setStyle("Bottom",
5);this._sandboxControlContainer.setStyle("Left",5);this._sandboxControlContainer.setStyle("Right",5);this._viewportSandboxStyleCode=new ViewportElement;this._viewportSandboxStyleCode.setStyle("Top",8);this._viewportSandboxStyleCode.setStyle("Bottom",8);this._viewportSandboxStyleCode.setStyle("Left",8);this._viewportSandboxStyleCode.setStyle("Right",8);this._textSandboxStyleCode=new TextElement;this._textSandboxStyleCode.setStyle("TextVerticalAlign","top");this._textSandboxStyleCode.setStyle("WordWrap",
!1);this._viewportSandboxStyleCode.setElement(this._textSandboxStyleCode);this._sandboxControlAndCodeContainer.addElement(this._sandboxControlPanelBackground);this._sandboxControlAndCodeContainer.addElement(this._sandboxControlContainer);this._sandboxControlAndCodeContainer.addElement(this._viewportSandboxStyleCode);this._sandboxCopyCodeContainer=new ListContainerElement;this._sandboxCopyCodeContainer.setStyle("PercentWidth",100);this._sandboxCopyCodeContainer.setStyle("MinWidth",200);this._sandboxCopyCodeContainer.setStyle("PaddingLeft",
5);this._sandboxCopyCodeContainer.setStyle("PaddingRight",5);this._toggleButtonCopyCode=new ToggleButtonElement;this._toggleButtonCopyCode.setStyle("PercentWidth",100);this._toggleButtonCopyCode.setStyle("AllowDeselect",!1);this._sandboxCopyCodeContainer.addElement(this._toggleButtonCopyCode);this._sandboxControlOuterContainer.addElement(this._sandboxControlAndCodeContainer);this._sandboxControlOuterContainer.addElement(this._sandboxCopyCodeContainer);this._sandboxInnerContainer.addElement(this._sandboxHeaderContainer);
this._sandboxInnerContainer.addElement(this._dividerSandbox);this._sandboxInnerContainer.addElement(this._sandboxControlOuterContainer);this._sandboxOuterContainer.addElement(this._sandboxPanelBackground);this._sandboxOuterContainer.addElement(this._sandboxInnerContainer);this._contentContainer.addElement(this._controlSelectOuterContainer);this._contentContainer.addElement(this._styleSelectOuterContainer);this._contentContainer.addElement(this._sandboxOuterContainer);this._dividerFooter=new CanvasElement;
this._dividerFooter.setStyleDefinitions(hDividerLineStyle);this._footerContainer=new ListContainerElement;this._footerContainer.setStyle("PercentWidth",100);this._footerContainer.setStyle("LayoutDirection","horizontal");this._footerContainer.setStyle("LayoutHorizontalAlign","right");this._labelPoweredBy=new LabelElement;this._labelFlexCanvasJS=new LabelElement;this._labelFlexCanvasJS.setStyle("TextStyle","bold italic");this._footerContainer.addElement(this._labelPoweredBy);this._footerContainer.addElement(this._labelFlexCanvasJS);
this._applicationContainer.addElement(this._headerContainer);this._applicationContainer.addElement(this._dividerHeader);this._applicationContainer.addElement(this._contentContainer);this._applicationContainer.addElement(this._dividerFooter);this._applicationContainer.addElement(this._footerContainer);this._applicationViewport.setElement(this._applicationContainer);this.addElement(this._applicationViewport);this._sandboxHeaderRadioButtonGroup=new ToggleButtonGroup;this._sandboxHeaderRadioButtonGroup.addButton(this._radioButtonSandbox);
this._sandboxHeaderRadioButtonGroup.addButton(this._radioButtonStyleCode);this._sandboxHeaderRadioButtonGroup.setSelectedButton(this._radioButtonSandbox);var a=this;this._onLocaleChangedInstance=function(b){a._onLocaleChanged(b)};this._onDropdownLocaleChangedInstance=function(b){a._onDropdownLocaleChanged(b)};this._onDataListControlsChangedInstance=function(b){a._onDataListControlsChanged(b)};this._onSandboxHeaderRadioButtonGroupChangedInstance=function(b){a._onSandboxHeaderRadioButtonGroupChanged(b)};
this._onStylingChangedInstance=function(b){a._onStylingChanged(b)};this._onEnterFrameStyleCodeUpdateInstance=function(b){a._onEnterFrameStyleCodeUpdate(b)};this._onButtonFontClickInstance=function(b){b.getTarget()==a._buttonFontSmaller?a._onButtonFontSmallerClick(b):a._onButtonFontLargerClick(b)};this._onToggleButtonCopyCodeEventHandlerInstance=function(b){"changed"==b.getType()?a._onToggleButtonCopyCodeChanged(b):"keydown"==b.getType()?a._onToggleButtonCopyCodeKeydown(b):"focusout"==b.getType()&&
a._onToggleButtonCopyCodeFocusout(b)};this._onCopyCutCodeInstance=function(b){window.removeEventListener("copy",a._onCopyCutCodeInstance);try{return b.clipboardData&&a._onCopyCutCode(b.clipboardData),b.preventDefault&&b.preventDefault(),!1}catch(l){}};this._onCopyCutCodeEnterFrameCleanupInstance=function(b){a.removeEventListener("enterframe",a._onCopyCutCodeEnterFrameCleanupInstance);window.removeEventListener("copy",a._onCopyCutCodeInstance)};this.addEventListener("localechanged",this._onLocaleChangedInstance);
this.addEventListener("stylingchanged",this._onStylingChangedInstance);this._dropdownLocale.addEventListener("changed",this._onDropdownLocaleChangedInstance);this._dataListControls.addEventListener("changed",this._onDataListControlsChangedInstance);this._sandboxHeaderRadioButtonGroup.addEventListener("changed",this._onSandboxHeaderRadioButtonGroupChangedInstance);this._buttonFontSmaller.addEventListener("click",this._onButtonFontClickInstance);this._buttonFontLarger.addEventListener("click",this._onButtonFontClickInstance);
this._toggleButtonCopyCode.addEventListener("changed",this._onToggleButtonCopyCodeEventHandlerInstance);this._toggleButtonCopyCode.addEventListener("keydown",this._onToggleButtonCopyCodeEventHandlerInstance);this._toggleButtonCopyCode.addEventListener("focusout",this._onToggleButtonCopyCodeEventHandlerInstance);var b=0;this._currentListRenderer=null;this._dropdownLocaleCollection=new ListCollection;this._dropdownLocaleCollection.addItem({key:"en-us",label:"English"});this._dropdownLocaleCollection.addItem({key:"es-es",
label:"Espa\u00f1ol"});this._dropdownLocale.setListCollection(this._dropdownLocaleCollection);this._dropdownLocale.setSelectedIndex(0);this._dataListControlsCollection=new ListCollection;b=new StyleDefinition;b.setStyle("Text","My Text");var c=new ButtonElement;c.setStyleDefinitions(b);var d=new ControlStyleType("","ButtonStyle","root",!1,!1,c,null,null,null);d.styleListCodeString="var ButtonStyle = new StyleDefinition();\r\n";d.buildControlStyleTypeLists(b);this._dataListControlsCollection.addItem({label:"Button",
control:c,rootControlStyleType:d,list:null});c=new SolidFill;c.setStyle("FillColor","#FFFF00");b=new StyleDefinition;b.setStyle("BackgroundFill",c);b.setStyle("Width",75);b.setStyle("Height",75);c=new CanvasElement;c.setStyleDefinitions(b);d=new ControlStyleType("","CanvasElementStyle","root",!1,!1,c,null,null,null);d.styleListCodeString="var CanvasElementStyle = new StyleDefinition();\r\n";d.buildControlStyleTypeLists(b);this._dataListControlsCollection.addItem({label:"CanvasElement",control:c,rootControlStyleType:d,
list:null});b=new StyleDefinition;c=new AlertElement;c.setStyleDefinitions(b);c.setTitleText("Lorem Ipsum");c.setContentText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat ultricies ante et semper.");c.setButtons(["Ante","Elit"]);d=new ControlStyleType("","AlertStyle","root",!1,!1,c,null,null,null);d.styleListCodeString="var AlertStyle = new StyleDefinition();\r\n";d.buildControlStyleTypeLists(b);this._dataListControlsCollection.addItem({label:"AlertElement",control:c,rootControlStyleType:d,
list:null});b=new StyleDefinition;b.setStyle("Text","My Text");c=new ToggleButtonElement;c.setStyleDefinitions(b);d=new ControlStyleType("","ToggleButtonStyle","root",!1,!1,c,null,null,null);d.styleListCodeString="var ToggleButtonStyle = new StyleDefinition();\r\n";d.buildControlStyleTypeLists(b);this._dataListControlsCollection.addItem({label:"ToggleButton",control:c,rootControlStyleType:d,list:null});b=new StyleDefinition;b.setStyle("Text","My Text");c=new RadioButtonElement;c.setStyleDefinitions(b);
d=new ControlStyleType("","RadioButtonStyle","root",!1,!1,c,null,null,null);d.styleListCodeString="var RadioButtonStyle = new StyleDefinition();\r\n";d.buildControlStyleTypeLists(b);this._dataListControlsCollection.addItem({label:"RadioButton",control:c,rootControlStyleType:d,list:null});b=new StyleDefinition;b.setStyle("Text","My Text");c=new CheckboxElement;c.setStyleDefinitions(b);d=new ControlStyleType("","CheckboxStyle","root",!1,!1,c,null,null,null);d.styleListCodeString="var CheckboxStyle = new StyleDefinition();\r\n";
d.buildControlStyleTypeLists(b);this._dataListControlsCollection.addItem({label:"Checkbox",control:c,rootControlStyleType:d,list:null});b=new StyleDefinition;c=new TextInputElement;c.setStyleDefinitions(b);d=new ControlStyleType("","TextInputStyle","root",!1,!1,c,null,null,null);d.styleListCodeString="var TextInputStyle = new StyleDefinition();\r\n";d.buildControlStyleTypeLists(b);this._dataListControlsCollection.addItem({label:"TextInput",control:c,rootControlStyleType:d,list:null});b=new StyleDefinition;
b.setStyle("Text","My Text");c=new LabelElement;c.setStyleDefinitions(b);d=new ControlStyleType("","LabelStyle","root",!1,!1,c,null,null,null);d.styleListCodeString="var LabelStyle = new StyleDefinition();\r\n";d.buildControlStyleTypeLists(b);this._dataListControlsCollection.addItem({label:"Label",control:c,rootControlStyleType:d,list:null});b=new StyleDefinition;b.setStyle("ImageSource",urlImgBlueMarble);c=new ImageElement;c.setStyleDefinitions(b);d=new ControlStyleType("","ImageStyle","root",!1,
!1,c,null,null,null);d.styleListCodeString="var ImageStyle = new StyleDefinition();\r\n";d.buildControlStyleTypeLists(b);this._dataListControlsCollection.addItem({label:"Image",control:c,rootControlStyleType:d,list:null});b=new StyleDefinition;b.setStyle("PercentWidth",100);b.setStyle("WordWrap",!0);b.setStyle("Multiline",!0);b.setStyle("Text","1) Lorem ipsum dolor sit amet, consectetur adipiscing elit.\r\n2) Cras posuere sem varius, luctus erat id, tincidunt nibh.\r\n3) Nam nec augue imperdiet massa porta ultricies nec vel eros.\r\n4) Nulla tincidunt quam vitae nisi hendrerit, ut commodo mauris pretium.\r\n5) Maecenas mattis ante in sapien lacinia, in consectetur urna vulputate.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam feugiat ultricies ante et semper. Quisque eget vulputate massa. In hac habitasse platea dictumst. Cras consequat leo nec mauris facilisis, vel bibendum dui vulputate. Nulla facilisi.");
c=new TextElement;c.setStyleDefinitions(b);d=new ControlStyleType("","TextStyle","root",!1,!1,c,null,null,null);d.styleListCodeString="var TextStyle = new StyleDefinition();\r\n";d.buildControlStyleTypeLists(b);this._dataListControlsCollection.addItem({label:"Text",control:c,rootControlStyleType:d,list:null});b=new StyleDefinition;b.setStyle("LayoutDirection","vertical");b.setStyle("PercentHeight",100);b.setStyle("PercentWidth",null);c=new ScrollBarElement;c.setStyleDefinitions(b);c.setScrollPageSize(1E3);
c.setScrollViewSize(150);c.setScrollLineSize(50);d=new ControlStyleType("","ScrollBarStyle","root",!1,!1,c,null,null,null);d.styleListCodeString="var ScrollBarStyle = new StyleDefinition();\r\n";d.buildControlStyleTypeLists(b);this._dataListControlsCollection.addItem({label:"ScrollBar",control:c,rootControlStyleType:d,list:null});b=new StyleDefinition;b.setStyle("PaddingTop",-1);b.setStyle("PaddingBottom",-1);d=new SolidFill;d.setStyle("FillColor","#FAFAFA");c=new StyleDefinition;c.setStyle("LayoutDirection",
"vertical");c.setStyle("PercentHeight",100);c.setStyle("Width",200);c.setStyle("BackgroundFill",d);c.setStyle("BorderType","solid");c.setStyle("BorderThickness",1);c.setStyle("PaddingTop",1);c.setStyle("PaddingLeft",1);c.setStyle("PaddingBottom",1);c.setStyle("ScrollBarStyle",b);d=new DataListElement;d.setStyleDefinitions(c);for(var e=new ListCollection,b=1;500>=b;b++)e.addItem("Data Item - "+b);d.setListCollection(e);b=new ControlStyleType("","DataListStyle","root",!1,!1,d,null,null,null);b.styleListCodeString=
"var DataListStyle = new StyleDefinition();\r\n";b.buildControlStyleTypeLists(c);this._dataListControlsCollection.addItem({label:"DataList",control:d,rootControlStyleType:b,list:null});c=new StyleDefinition;c.setStyle("Text","My Text");d=new DropdownElement;d.setStyleDefinitions(c);e=new ListCollection;for(b=1;50>=b;b++)e.addItem("Data Item - "+b);d.setListCollection(e);b=new ControlStyleType("","DropdownStyle","root",!1,!1,d,null,null,null);b.styleListCodeString="var DropdownStyle = new StyleDefinition();\r\n";
b.buildControlStyleTypeLists(c);this._dataListControlsCollection.addItem({label:"Dropdown",control:d,rootControlStyleType:b,list:null});c=new SolidFill;c.setStyle("FillColor","#FFFFFF");b=new StyleDefinition;b.setStyle("PercentWidth",75);b.setStyle("PercentHeight",50);b.setStyle("BackgroundFill",c);b.setStyle("LayoutDirection","vertical");c=new ListContainerElement;c.setStyleDefinitions(b);d=new ButtonElement;d.setStyle("Text","Measured X Measured");e=new ButtonElement;e.setStyle("Text","25% X 25%");
e.setStyle("PercentWidth",25);e.setStyle("PercentHeight",25);var f=new ButtonElement;f.setStyle("Text","50% X 50%");f.setStyle("PercentWidth",50);f.setStyle("PercentHeight",50);c.addElement(d);c.addElement(e);c.addElement(f);d=new ControlStyleType("","ListContainerStyle","root",!1,!1,c,null,null,null);d.styleListCodeString="var ListContainerStyle = new StyleDefinition();\r\n";d.buildControlStyleTypeLists(b);this._dataListControlsCollection.addItem({label:"ListContainer",control:c,rootControlStyleType:d,
list:null});var g=new StyleDefinition;g.setStyle("PercentWidth",100);g.setStyle("PercentHeight",100);c=new DataGridElement;c.setStyleDefinitions(g);f=new DataGridColumnDefinition;f.setStyle("RowItemLabelFunction",function(a,b){return a.col1});f.setStyle("CollectionSort",new CollectionSort(function(a,b){return a.col1<b.col1?-1:a.col1>b.col1?1:0}));f.setStyle("HeaderText","Column1");c.addColumnDefinition(f);e=new DataGridColumnDefinition;e.setStyle("RowItemLabelFunction",function(a,b){return a.col2});
e.setStyle("CollectionSort",new CollectionSort(function(a,b){return a.col2<b.col2?-1:a.col2>b.col2?1:0}));e.setStyle("HeaderText","Column2");c.addColumnDefinition(e);b=new StyleDefinition;b.setStyle("TextHorizontalAlign","right");b.setStyle("PaddingRight",18);var h=new StyleDefinition;h.setStyle("TextHorizontalAlign","right");d=new DataGridColumnDefinition;d.setStyle("RowItemLabelFunction",function(a,b){return a.col3});d.setStyle("CollectionSort",new CollectionSort(function(a,b){return Number(a.col3)<
Number(b.col3)?-1:Number(a.col3)>Number(b.col3)?1:0}));d.setStyle("HeaderText","Column3");d.setStyle("HeaderItemStyle",b);d.setStyle("RowItemStyle",h);c.addColumnDefinition(d);h=new ListCollection;for(b=1;500>=b;b++)h.addItem({col1:"Column1 Data "+b,col2:"Column2 Data "+b,col3:b.toString()});c.setListCollection(h);b=new ControlStyleType("","DataGridStyle","root",!1,!1,c,null,null,null);b.styleListCodeString="var DataGridStyle = new StyleDefinition();\r\n";b.buildControlStyleTypeLists(g);g=new ControlStyleType("",
"DataGridColumn1Style","class",!1,!1,c,null,null,null);g.styleListCodeString="var DataGridColumn1Style = new DataGridColumnDefinition();\r\n";g.buildControlStyleTypeLists(f);f=new ControlStyleType("","DataGridColumn2Style","class",!1,!1,c,null,null,null);f.styleListCodeString="var DataGridColumn2Style = new DataGridColumnDefinition();\r\n";f.buildControlStyleTypeLists(e);e=new ControlStyleType("","DataGridColumn3Style","class",!1,!1,c,null,null,null);e.styleListCodeString="var DataGridColumn3Style = new DataGridColumnDefinition();\r\n";
e.buildControlStyleTypeLists(d);this._dataListControlsCollection.addItem({label:"DataGrid",control:c,rootControlStyleType:[b,g,f,e],list:null});this._dataListControlsCollection.setCollectionSort(new CollectionSort(StyleExplorerApplication.LabelSortFunction));this._dataListControlsCollection.sort();this._dataListControls.setListCollection(this._dataListControlsCollection);this._onSandboxHeaderRadioButtonGroupChanged(null)}StyleExplorerApplication.prototype=Object.create(CanvasManager.prototype);
StyleExplorerApplication.prototype.constructor=StyleExplorerApplication;StyleExplorerApplication.base=CanvasManager;StyleExplorerApplication.LabelSortFunction=function(a,b){return a.label<b.label?-1:a.label>b.label?1:0};
StyleExplorerApplication.prototype._onLocaleChanged=function(a){a=this.getManager().getLocale();this._labelFontSize.setStyle("Text",localeStrings[a]["Text Size"]);this._textTitle.setStyle("Text",localeStrings.all.FlexCanvasJS+" "+localeStrings.all["Style Explorer"]);this._labelLanguage.setStyle("Text",localeStrings[a].Language);this._labelPoweredBy.setStyle("Text",localeStrings[a]["Powered By"]+" ");this._labelFlexCanvasJS.setStyle("Text",localeStrings.all.FlexCanvasJS);this._labelSelectControl.setStyle("Text",
localeStrings[a]["Select Control"]);this._labelSelectStyle.setStyle("Text",localeStrings[a]["Select Styles"]);this._radioButtonSandbox.setStyle("Text",localeStrings[a].Sandbox+" (AnchorContainer)");this._radioButtonStyleCode.setStyle("Text",localeStrings[a]["Style Code"]);this._toggleButtonCopyCode.setStyle("Text",localeStrings[a].Copy+" "+localeStrings[a]["Style Code"])};
StyleExplorerApplication.prototype._onButtonFontLargerClick=function(a){a=this.getStyle("TextSize");this.setStyle("TextSize",a+2);16==a+2&&this._buttonFontLarger.setStyle("Enabled",!1);this._buttonFontSmaller.setStyle("Enabled",!0)};StyleExplorerApplication.prototype._onButtonFontSmallerClick=function(a){a=this.getStyle("TextSize");this.setStyle("TextSize",a-2);12==a-2&&this._buttonFontSmaller.setStyle("Enabled",!1);this._buttonFontLarger.setStyle("Enabled",!0)};
StyleExplorerApplication.prototype._onSandboxHeaderRadioButtonGroupChanged=function(a){this._sandboxHeaderRadioButtonGroup.getSelectedButton()==this._radioButtonSandbox?(this._sandboxControlContainer.setStyle("Visible",!0),this._viewportSandboxStyleCode.setStyle("Visible",!1),this._sandboxCopyCodeContainer.setStyle("Visible",!1),this._sandboxCopyCodeContainer.setStyle("IncludeInLayout",!1)):(this._sandboxControlContainer.setStyle("Visible",!1),this._viewportSandboxStyleCode.setStyle("Visible",!0),
this._sandboxCopyCodeContainer.setStyle("Visible",!0),this._sandboxCopyCodeContainer.setStyle("IncludeInLayout",!0))};StyleExplorerApplication.prototype._onDropdownLocaleChanged=function(a){this.getManager().setLocale(this._dropdownLocale.getSelectedItem().key)};
StyleExplorerApplication.prototype._onDataListControlsChanged=function(a){for(;0<this._sandboxControlContainer.getNumElements();)this._sandboxControlContainer.removeElementAt(0);if(-1==this._dataListControls.getSelectedIndex())this._textSandboxStyleCode.setStyle("Text","");else{a=this._dataListControls.getSelectedItem();this._sandboxControlContainer.addElement(a.control);if(null==a.list){if(Array.isArray(a.rootControlStyleType)){a.list=new ListContainerElement;a.list.setStyle("PercentWidth",100);
a.list.setStyle("LayoutGap",4);for(var b=0;b<a.rootControlStyleType.length;b++){var c=new StyleListRenderer;c.setStyleControlType(a.rootControlStyleType[b]);a.list.addElement(c);b!=a.rootControlStyleType.length-1&&c.setStyle("PaddingBottom",12);b<a.rootControlStyleType.length-1&&(c=new CanvasElement,c.setStyleDefinitions(hDividerLineStyle),a.list.addElement(c))}}else a.list=new StyleListRenderer,a.list.setStyleControlType(a.rootControlStyleType);this._stylesControlContainer.addElement(a.list)}null!=
this._currentListRenderer&&(this._currentListRenderer.setStyle("Visible",!1),this._currentListRenderer.setStyle("IncludeInLayout",!1));this._currentListRenderer=a.list;null!=this._currentListRenderer&&(this._currentListRenderer.setStyle("Visible",!0),this._currentListRenderer.setStyle("IncludeInLayout",!0));this._onStylingChanged(null)}};
StyleExplorerApplication.prototype._onStylingChanged=function(a){0==this.hasEventListener("enterframe",this._onEnterFrameStyleCodeUpdateInstance)&&this.addEventListener("enterframe",this._onEnterFrameStyleCodeUpdateInstance)};
StyleExplorerApplication.prototype._onEnterFrameStyleCodeUpdate=function(a){this.removeEventListener("enterframe",this._onEnterFrameStyleCodeUpdateInstance);a=this._dataListControls.getSelectedItem().rootControlStyleType;if(Array.isArray(a))for(var b="",c=0;c<a.length;c++)b+=a[c].generateStylingCode();else b=a.generateStylingCode();this._textSandboxStyleCode.setStyle("Text",b)};
StyleExplorerApplication.prototype._onToggleButtonCopyCodeChanged=function(a){this._toggleButtonCopyCode.setStyle("Text",localeStrings[this.getManager().getLocale()]["Press Ctrl C"])};StyleExplorerApplication.prototype._onToggleButtonCopyCodeKeydown=function(a){"c"==a.getKey()&&1==a.getCtrl()&&(window.clipboardData?(this._onCopyCutCode(window.clipboardData),a.preventDefault()):(window.addEventListener("copy",this._onCopyCutCodeInstance),this.addEventListener("enterframe",this._onCopyCutCodeEnterFrameCleanupInstance)))};
StyleExplorerApplication.prototype._onToggleButtonCopyCodeFocusout=function(a){a=this.getManager().getLocale();this._toggleButtonCopyCode.setSelected(!1);this._toggleButtonCopyCode.setStyle("Text",localeStrings[a].Copy+" "+localeStrings[a]["Style Code"])};StyleExplorerApplication.prototype._onCopyCutCode=function(a){a.setData("Text",this._textSandboxStyleCode.getStyle("Text"));this._onToggleButtonCopyCodeFocusout(null)};
function ControlStyleType(a,b,c,d,e,f,g,h,k){this.category=a;this.styleName=b;this.styleType=c;this.allowNull=d;this.initNull=e;this.initValue=h;this.allowValues=k;this.styleDefinition=f;this.parent=g;this.styleItemCodeString=this.styleListCodeString="";this.styleList=new ListCollection;null==ControlStyleType.StyleCategoryNameSort&&(ControlStyleType.StyleCategoryNameSort=new CollectionSort(ControlStyleType.StyleCategoryNameSortFunction,!1));this.styleList.setCollectionSort(ControlStyleType.StyleCategoryNameSort)}
ControlStyleType.prototype.constructor=ControlStyleType;ControlStyleType.StyleCategoryNameSortFunction=function(a,b){return a.category<b.category?-1:a.category>b.category?1:a.styleName<b.styleName?-1:a.styleName>b.styleName?1:0};ControlStyleType.StyleCategoryNameSort=null;
ControlStyleType._GenerateStylingCodeRecurse=function(a,b,c){if(""!=b.styleListCodeString){for(var d={value:b.styleListCodeString},e=0;e<b.styleList.getLength();e++)ControlStyleType._GenerateStylingCodeRecurse(a,b.styleList.getItemAt(e),d);a.push(d)}null!=c&&""!=b.styleItemCodeString&&(c.value+=b.styleItemCodeString)};ControlStyleType.prototype.hasParentStyleName=function(a){for(var b=this.parent;null!=b;){if(b.styleName==a)return!0;b=b.parent}return!1};
ControlStyleType.prototype.generateStylingCode=function(){var a=[];ControlStyleType._GenerateStylingCodeRecurse(a,this,null);for(var b="",c=0;c<a.length;c++)b+=a[c].value+"\r\n";return b};
ControlStyleType.prototype.buildControlStyleTypeLists=function(a){null==a&&(a=this.styleDefinition.getStyle(this.styleName));this.styleList.clear();if(0!=a instanceof StyleDefinition){"root"==this.styleType&&(this.styleList.addItem(new ControlStyleType("Container","Top","number",!0,!0,a,this,10,null)),this.styleList.addItem(new ControlStyleType("Container","Bottom","number",!0,!0,a,this,10,null)),this.styleList.addItem(new ControlStyleType("Container","Left","number",!0,!0,a,this,10,null)),this.styleList.addItem(new ControlStyleType("Container",
"Right","number",!0,!0,a,this,10,null)),this.styleList.addItem(new ControlStyleType("Container","X","number",!0,!0,a,this,10,null)),this.styleList.addItem(new ControlStyleType("Container","Y","number",!0,!0,a,this,10,null)),this.styleList.addItem(new ControlStyleType("Container","HorizontalCenter","number",!0,!0,a,this,0,null)),this.styleList.addItem(new ControlStyleType("Container","VerticalCenter","number",!0,!0,a,this,0,null)),this.styleList.addItem(new ControlStyleType("Container","RotateDegrees",
"number",!1,!1,a,this,0,null)),this.styleList.addItem(new ControlStyleType("Container","RotateCenterY","number",!0,!0,a,this,50,null)),this.styleList.addItem(new ControlStyleType("Container","RotateCenterY","number",!0,!0,a,this,50,null)),this.styleList.addItem(new ControlStyleType("Functional","Draggable","bool",!1,!1,a,this,!1,[{label:"true",value:!0},{label:"false",value:!1}])));if("root"==this.styleType||"ButtonIncrementStyle"==this.styleName||"ButtonDecrementStyle"==this.styleName||"ButtonTrackStyle"==
this.styleName||"ButtonTabStyle"==this.styleName||"AlertButtonStyle"==this.styleName||"AlertContentListContainerStyle"==this.styleName||"AlertButtonListContainerStyle"==this.styleName||"AlertTitleLabelStyle"==this.styleName||"AlertContentTextStyle"==this.styleName)this.styleList.addItem(new ControlStyleType("Container","PercentWidth","number",!0,!0,a,this,50,null)),this.styleList.addItem(new ControlStyleType("Container","PercentHeight","number",!0,!0,a,this,50,null)),this.styleList.addItem(new ControlStyleType("Container",
"MaxWidth","number",!0,!0,a,this,50,null)),this.styleList.addItem(new ControlStyleType("Container","MaxHeight","number",!0,!0,a,this,50,null));if("root"==this.styleType||"ButtonIncrementStyle"==this.styleName||"ButtonDecrementStyle"==this.styleName||"ButtonTrackStyle"==this.styleName||"ButtonTabStyle"==this.styleName||"AlertButtonStyle"==this.styleName||"HeaderItemStyle"==this.styleName||"RowItemStyle"==this.styleName||"ListItemStyle"==this.styleName||"AlertContentListContainerStyle"==this.styleName||
"AlertButtonListContainerStyle"==this.styleName||"AlertTitleLabelStyle"==this.styleName||"AlertContentTextStyle"==this.styleName)0==this.hasParentStyleName("DataGridStyle")&&"HeaderItemStyle"!=this.styleName&&"RowItemStyle"!=this.styleName&&this.styleList.addItem(new ControlStyleType("Container","MinWidth","number",!0,!0,a,this,50,null)),this.styleList.addItem(new ControlStyleType("Container","MinHeight","number",!0,!0,a,this,50,null));if("root"==this.styleType||"ButtonIncrementStyle"==this.styleName||
"ButtonDecrementStyle"==this.styleName||"ButtonTrackStyle"==this.styleName||"ButtonTabStyle"==this.styleName||"AlertButtonStyle"==this.styleName||"ArrowButtonStyle"==this.styleName||"ColumnDividerStyle"==this.styleName||"VerticalGridLinesStyle"==this.styleName||"HorizontalGridLinesStyle"==this.styleName||"ScrollBarStyle"==this.styleName||"SortAscIconStyle"==this.styleName||"SortDescIconStyle"==this.styleName||"HeaderItemStyle"==this.styleName||"RowItemStyle"==this.styleName||"ListItemStyle"==this.styleName||
"AlertContentListContainerStyle"==this.styleName||"AlertButtonListContainerStyle"==this.styleName||"AlertTitleLabelStyle"==this.styleName||"AlertContentTextStyle"==this.styleName){var b=10;if("root"==this.styleType)b=50;else if("VerticalGridLinesStyle"==this.styleName||"HorizontalGridLinesStyle"==this.styleName)b=1;0==this.hasParentStyleName("DataGridStyle")&&"HeaderItemStyle"!=this.styleName&&"RowItemStyle"!=this.styleName&&this.styleList.addItem(new ControlStyleType("Container","Width","number",
!0,!0,a,this,b,null));this.styleList.addItem(new ControlStyleType("Container","Height","number",!0,!0,a,this,b,null))}if("root"==this.styleType||"ButtonIncrementStyle"==this.styleName||"ButtonDecrementStyle"==this.styleName||"ButtonTrackStyle"==this.styleName||"ButtonTabStyle"==this.styleName||"AlertButtonStyle"==this.styleName||"ArrowButtonStyle"==this.styleName||"PopupDataListStyle"==this.styleName||"HeaderStyle"==this.styleName||"ColumnDividerStyle"==this.styleName||"VerticalGridLinesStyle"==this.styleName||
"HorizontalGridLinesStyle"==this.styleName||"ListItemStyle"==this.styleName||"HeaderItemStyle"==this.styleName||"RowItemStyle"==this.styleName||"SortAscIconStyle"==this.styleName||"SortDescIconStyle"==this.styleName||"AlertContentListContainerStyle"==this.styleName||"AlertButtonListContainerStyle"==this.styleName||0<=this.styleName.indexOf("SkinStyle"))this.styleList.addItem(new ControlStyleType("Rendering","Alpha","number",!1,!1,a,this,.5,null)),this.styleList.addItem(new ControlStyleType("Rendering",
"BackgroundShape","class",!0,!0,a,this,RoundedRectangleShape,[{label:"RoundedRectangle",value:RoundedRectangleShape},{label:"Arrow",value:ArrowShape},{label:"Ellipse",value:EllipseShape}])),this.styleList.addItem(new ControlStyleType("Rendering","BackgroundFill","class",!0,!1,a,this,SolidFill,[{label:"Solid",value:SolidFill},{label:"LinearGradient",value:LinearGradientFill}])),this.styleList.addItem(new ControlStyleType("Rendering","BorderType","string",!0,!1,a,this,"solid",[{label:"solid",value:"solid"},
{label:"inset",value:"inset"},{label:"outset",value:"outset"}])),this.styleList.addItem(new ControlStyleType("Rendering","BorderColor","color",!0,!1,a,this,"#000000",null)),this.styleList.addItem(new ControlStyleType("Rendering","BorderThickness","number",!1,!1,a,this,1,null)),this.styleList.addItem(new ControlStyleType("Rendering","ShadowSize","number",!1,!1,a,this,0,null)),this.styleList.addItem(new ControlStyleType("Rendering","ShadowOffsetX","number",!1,!1,a,this,0,null)),this.styleList.addItem(new ControlStyleType("Rendering",
"ShadowOffsetY","number",!1,!1,a,this,0,null)),this.styleList.addItem(new ControlStyleType("Rendering","ShadowColor","color",!1,!1,a,this,"#000000",null));"root"!=this.styleType&&"ButtonIncrementStyle"!=this.styleName&&"ButtonDecrementStyle"!=this.styleName&&"ButtonTrackStyle"!=this.styleName&&"ButtonTabStyle"!=this.styleName&&"ColumnDividerStyle"!=this.styleName||this.styleList.addItem(new ControlStyleType("Functional","Visible","bool",!1,!1,a,this,!0,[{label:"true",value:!0},{label:"false",value:!1}]));
"root"!=this.styleType&&"ButtonIncrementStyle"!=this.styleName&&"ButtonDecrementStyle"!=this.styleName&&"ButtonTrackStyle"!=this.styleName&&"ButtonTabStyle"!=this.styleName&&"AlertButtonStyle"!=this.styleName&&"HeaderStyle"!=this.styleName&&"ColumnDividerStyle"!=this.styleName&&"HeaderItemStyle"!=this.styleName&&"RowItemStyle"!=this.styleName||this.styleList.addItem(new ControlStyleType("Functional","Cursor","string",!0,!0,a,this,!1,[{label:"pointer",value:"pointer"},{label:"text",value:"text"},{label:"none",
value:"none"}]));if("LabelStyle"==this.styleName||"AlertTitleLabelStyle"==this.styleName||"AlertContentTextStyle"==this.styleName||"TextInputStyle"==this.styleName||"ButtonStyle"==this.styleName||"AlertButtonStyle"==this.styleName||"ToggleButtonStyle"==this.styleName||"RadioButtonStyle"==this.styleName||"CheckboxStyle"==this.styleName||"DataListStyle"==this.styleName||"ListItemStyle"==this.styleName||"DropdownStyle"==this.styleName||"PopupDataListStyle"==this.styleName||"DataGridStyle"==this.styleName||
"HeaderStyle"==this.styleName||"HeaderItemStyle"==this.styleName||"RowItemStyle"==this.styleName||"TextStyle"==this.styleName)this.styleList.addItem(new ControlStyleType("Text","TextColor","color",!1,!1,a,this,"#000000",null)),this.styleList.addItem(new ControlStyleType("Text","TextStyle","string",!1,!1,a,this,"normal",[{label:"normal",value:"normal"},{label:"bold",value:"bold"},{label:"italic",value:"italic"},{label:"bold italic",value:"bold italic"}])),this.styleList.addItem(new ControlStyleType("Text",
"TextFont","string",!1,!1,a,this,"Arial",[{label:"Arial",value:"Arial"},{label:"Times New Roman",value:"Times New Roman"},{label:"Comic Sans MS",value:"Comic Sans MS"},{label:"Verdana",value:"Verdana"},{label:"Roboto (Google)",value:"Roboto"}])),this.styleList.addItem(new ControlStyleType("Text","TextSize","number",!1,!1,a,this,12,null)),this.styleList.addItem(new ControlStyleType("Text","TextHorizontalAlign","string",!1,!1,a,this,"center",[{label:"left",value:"left"},{label:"center",value:"center"},
{label:"right",value:"right"}])),this.styleList.addItem(new ControlStyleType("Text","TextVerticalAlign","string",!1,!1,a,this,"middle",[{label:"top",value:"top"},{label:"middle",value:"middle"},{label:"bottom",value:"bottom"}])),this.styleList.addItem(new ControlStyleType("Text","TextLinePaddingTop","number",!1,!1,a,this,1,null)),this.styleList.addItem(new ControlStyleType("Text","TextLinePaddingBottom","number",!1,!1,a,this,1,null)),this.styleList.addItem(new ControlStyleType("Text","TextFillType",
"string",!1,!1,a,this,"fill",[{label:"fill",value:"fill"},{label:"stroke",value:"stroke"}]));if("LabelStyle"==this.styleName||"AlertStyle"==this.styleName||"AlertTitleLabelStyle"==this.styleName||"AlertContentTextStyle"==this.styleName||"AlertContentListContainerStyle"==this.styleName||"AlertButtonListContainerStyle"==this.styleName||"TextInputStyle"==this.styleName||"ButtonStyle"==this.styleName||"AlertButtonStyle"==this.styleName||"ToggleButtonStyle"==this.styleName||"RadioButtonStyle"==this.styleName||
"CheckboxStyle"==this.styleName||"ScrollBarStyle"==this.styleName||"ButtonIncrementStyle"==this.styleName||"ButtonDecrementStyle"==this.styleName||"ButtonTrackStyle"==this.styleName||"ButtonTabStyle"==this.styleName||"ListItemStyle"==this.styleName||"DataListStyle"==this.styleName||"DropdownStyle"==this.styleName||"PopupDataListStyle"==this.styleName||"ListContainerStyle"==this.styleName||"DataGridStyle"==this.styleName||"HeaderStyle"==this.styleName||"HeaderItemStyle"==this.styleName||"RowItemStyle"==
this.styleName||"TextStyle"==this.styleName)this.styleList.addItem(new ControlStyleType("Layout","Padding","number",!1,!1,a,this,2,null)),this.styleList.addItem(new ControlStyleType("Layout","PaddingTop","number",!1,!1,a,this,2,null)),this.styleList.addItem(new ControlStyleType("Layout","PaddingBottom","number",!1,!1,a,this,2,null)),this.styleList.addItem(new ControlStyleType("Layout","PaddingRight","number",!1,!1,a,this,2,null)),this.styleList.addItem(new ControlStyleType("Layout","PaddingLeft",
"number",!1,!1,a,this,2,null));"LabelStyle"!=this.styleName&&"ButtonStyle"!=this.styleName&&"ToggleButtonStyle"!=this.styleName&&"RadioButtonStyle"!=this.styleName&&"CheckboxStyle"!=this.styleName&&"DropdownStyle"!=this.styleName||this.styleList.addItem(new ControlStyleType("Functional","Text","string",!0,!1,a,this,"My Text",null));"TextInputStyle"!=this.styleName&&"ButtonStyle"!=this.styleName&&"ToggleButtonStyle"!=this.styleName&&"RadioButtonStyle"!=this.styleName&&"CheckboxStyle"!=this.styleName&&
"ScrollBarStyle"!=this.styleName&&"ButtonIncrementStyle"!=this.styleName&&"ButtonDecrementStyle"!=this.styleName&&"ButtonTrackStyle"!=this.styleName&&"ButtonTabStyle"!=this.styleName&&"DropdownStyle"!=this.styleName&&"HeaderItemStyle"!=this.styleName&&"SortAscIconStyle"!=this.styleName&&"SortDescIconStyle"!=this.styleName||this.styleList.addItem(new ControlStyleType("Functional","Enabled","bool",!1,!1,a,this,!0,[{label:"true",value:!0},{label:"false",value:!1}]));("ButtonStyle"==this.styleName||"ToggleButtonStyle"==
this.styleName||"RadioButtonStyle"==this.styleName||"CheckboxStyle"==this.styleName||"ButtonIncrementStyle"==this.styleName||"ButtonDecrementStyle"==this.styleName||"ButtonTrackStyle"==this.styleName||"ButtonTabStyle"==this.styleName||"AlertButtonStyle"==this.styleName||"TextInputStyle"==this.styleName||"ListItemStyle"==this.styleName&&(this.hasParentStyleName("DataListStyle")||this.hasParentStyleName("PopupDataListStyle"))||"DropdownStyle"==this.styleName||"ArrowButtonStyle"==this.styleName||"ColumnDividerStyle"==
this.styleName||"HeaderItemStyle"==this.styleName||"RowItemStyle"==this.styleName||"SortAscIconStyle"==this.styleName||"SortDescIconStyle"==this.styleName)&&this.styleList.addItem(new ControlStyleType("Sub Styles","UpSkinStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}]));("ButtonStyle"==this.styleName||"AlertButtonStyle"==this.styleName||"ToggleButtonStyle"==this.styleName||"RadioButtonStyle"==this.styleName||"CheckboxStyle"==this.styleName||"TextInputStyle"==
this.styleName||"ListItemStyle"==this.styleName&&(this.hasParentStyleName("DataListStyle")||this.hasParentStyleName("PopupDataListStyle"))||"DropdownStyle"==this.styleName||"HeaderItemStyle"==this.styleName||"RowItemStyle"==this.styleName)&&this.styleList.addItem(new ControlStyleType("Text","UpTextColor","color",!1,!1,a,this,"#000000",null));"ButtonStyle"!=this.styleName&&"ToggleButtonStyle"!=this.styleName&&"RadioButtonStyle"!=this.styleName&&"CheckboxStyle"!=this.styleName&&"ButtonIncrementStyle"!=
this.styleName&&"ButtonDecrementStyle"!=this.styleName&&"ButtonTrackStyle"!=this.styleName&&"ButtonTabStyle"!=this.styleName&&"TextInputStyle"!=this.styleName&&"DropdownStyle"!=this.styleName&&"ArrowButtonStyle"!=this.styleName&&"ColumnDividerStyle"!=this.styleName&&"HeaderItemStyle"!=this.styleName&&"SortAscIconStyle"!=this.styleName&&"SortDescIconStyle"!=this.styleName||this.styleList.addItem(new ControlStyleType("Sub Styles","DisabledSkinStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",
value:StyleDefinition}]));"ButtonStyle"!=this.styleName&&"ToggleButtonStyle"!=this.styleName&&"RadioButtonStyle"!=this.styleName&&"CheckboxStyle"!=this.styleName&&"TextInputStyle"!=this.styleName&&"DropdownStyle"!=this.styleName&&"HeaderItemStyle"!=this.styleName||this.styleList.addItem(new ControlStyleType("Text","DisabledTextColor","color",!1,!1,a,this,"#000000",null));("ButtonStyle"==this.styleName||"AlertButtonStyle"==this.styleName||"ToggleButtonStyle"==this.styleName||"RadioButtonStyle"==this.styleName||
"CheckboxStyle"==this.styleName||"ButtonIncrementStyle"==this.styleName||"ButtonDecrementStyle"==this.styleName||"ButtonTrackStyle"==this.styleName||"ButtonTabStyle"==this.styleName||"ListItemStyle"==this.styleName&&(this.hasParentStyleName("DataListStyle")||this.hasParentStyleName("PopupDataListStyle"))||"DropdownStyle"==this.styleName||"ArrowButtonStyle"==this.styleName||"ColumnDividerStyle"==this.styleName||"HeaderItemStyle"==this.styleName||"RowItemStyle"==this.styleName||"SortAscIconStyle"==
this.styleName||"SortDescIconStyle"==this.styleName)&&this.styleList.addItem(new ControlStyleType("Sub Styles","OverSkinStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}]));("ButtonStyle"==this.styleName||"AlertButtonStyle"==this.styleName||"ToggleButtonStyle"==this.styleName||"RadioButtonStyle"==this.styleName||"CheckboxStyle"==this.styleName||"ListItemStyle"==this.styleName&&(this.hasParentStyleName("DataListStyle")||this.hasParentStyleName("PopupDataListStyle"))||
"DropdownStyle"==this.styleName||"HeaderItemStyle"==this.styleName||"RowItemStyle"==this.styleName)&&this.styleList.addItem(new ControlStyleType("Text","OverTextColor","color",!1,!1,a,this,"#000000",null));"ButtonStyle"!=this.styleName&&"AlertButtonStyle"!=this.styleName&&"ToggleButtonStyle"!=this.styleName&&"RadioButtonStyle"!=this.styleName&&"CheckboxStyle"!=this.styleName&&"ButtonIncrementStyle"!=this.styleName&&"ButtonDecrementStyle"!=this.styleName&&"ButtonTrackStyle"!=this.styleName&&"ButtonTabStyle"!=
this.styleName&&"DropdownStyle"!=this.styleName&&"ArrowButtonStyle"!=this.styleName&&"ColumnDividerStyle"!=this.styleName&&"HeaderItemStyle"!=this.styleName&&"SortAscIconStyle"!=this.styleName&&"SortDescIconStyle"!=this.styleName||this.styleList.addItem(new ControlStyleType("Sub Styles","DownSkinStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}]));"ButtonStyle"!=this.styleName&&"AlertButtonStyle"!=this.styleName&&"ToggleButtonStyle"!=this.styleName&&"RadioButtonStyle"!=
this.styleName&&"CheckboxStyle"!=this.styleName&&"DropdownStyle"!=this.styleName&&"HeaderItemStyle"!=this.styleName||this.styleList.addItem(new ControlStyleType("Text","DownTextColor","color",!1,!1,a,this,"#000000",null));"DropdownStyle"==this.styleName&&(this.styleList.addItem(new ControlStyleType("Functional","MaxPopupHeight","number",!1,!1,a,this,200,null)),this.styleList.addItem(new ControlStyleType("Functional","OpenCloseTweenDuration","number",!1,!1,a,this,300,null)),this.styleList.addItem(new ControlStyleType("Layout",
"PopupDataListClipTopOrBottom","number",!1,!1,a,this,1,null)),this.styleList.addItem(new ControlStyleType("Sub Styles","PopupDataListStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}])),this.styleList.addItem(new ControlStyleType("Sub Styles","ArrowButtonStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}])));if("ListItemStyle"==this.styleName&&(this.hasParentStyleName("DataListStyle")||this.hasParentStyleName("PopupDataListStyle"))||
"RowItemStyle"==this.styleName)this.styleList.addItem(new ControlStyleType("Sub Styles","AltSkinStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}])),this.styleList.addItem(new ControlStyleType("Sub Styles","SelectedSkinStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}])),this.styleList.addItem(new ControlStyleType("Text","AltTextColor","color",!1,!1,a,this,"#000000",null)),this.styleList.addItem(new ControlStyleType("Text",
"SelectedTextColor","color",!1,!1,a,this,"#000000",null));"TextInputStyle"==this.styleName&&(this.styleList.addItem(new ControlStyleType("Functional","MaxChars","number",!1,!1,a,this,0,null)),this.styleList.addItem(new ControlStyleType("Functional","DisplayAsPassword","bool",!1,!1,a,this,!0,[{label:"true",value:!0},{label:"false",value:!1}])),this.styleList.addItem(new ControlStyleType("Text","TextHighlightedColor","color",!1,!1,a,this,"#FFFFFF",null)),this.styleList.addItem(new ControlStyleType("Text",
"TextHighlightedBackgroundColor","color",!1,!1,a,this,"#000000",null)),this.styleList.addItem(new ControlStyleType("Text","UpTextHighlightedColor","color",!1,!1,a,this,"#FFFFFF",null)),this.styleList.addItem(new ControlStyleType("Text","UpTextHighlightedBackgroundColor","color",!1,!1,a,this,"#000000",null)),this.styleList.addItem(new ControlStyleType("Text","DisabledTextHighlightedColor","color",!1,!1,a,this,"#FFFFFF",null)),this.styleList.addItem(new ControlStyleType("Text","DisabledTextHighlightedBackgroundColor",
"color",!1,!1,a,this,"#000000",null)),this.styleList.addItem(new ControlStyleType("Text","TextCaretColor","color",!1,!1,a,this,"#000000",null)));"LabelStyle"!=this.styleName&&"AlertTitleLabelStyle"!=this.styleName||this.styleList.addItem(new ControlStyleType("Functional","TruncateToFit","string",!1,!1,a,this,"...",null));"ImageStyle"==this.styleName&&(this.styleList.addItem(new ControlStyleType("Rendering","ImageSourceClipX","number",!0,!0,a,this,0,null)),this.styleList.addItem(new ControlStyleType("Rendering",
"ImageSourceClipY","number",!0,!0,a,this,0,null)),this.styleList.addItem(new ControlStyleType("Rendering","ImageSourceClipWidth","number",!0,!0,a,this,150,null)),this.styleList.addItem(new ControlStyleType("Rendering","ImageSourceClipHeight","number",!0,!0,a,this,150,null)),this.styleList.addItem(new ControlStyleType("Rendering","ImageScaleType","string",!0,!0,a,this,0,[{label:"fit",value:"fit"},{label:"stretch",value:"stretch"},{label:"tile",value:"tile"},{label:"tilefit",value:"tilefit"}])),this.styleList.addItem(new ControlStyleType("Layout",
"ImageVerticalAlign","string",!1,!1,a,this,"middle",[{label:"top",value:"top"},{label:"middle",value:"middle"},{label:"bottom",value:"bottom"}])),this.styleList.addItem(new ControlStyleType("Layout","ImageHorizontalAlign","string",!1,!1,a,this,"center",[{label:"left",value:"left"},{label:"center",value:"center"},{label:"right",value:"right"}])));if("TextStyle"==this.styleName||"AlertContentTextStyle"==this.styleName)this.styleList.addItem(new ControlStyleType("Text","Multiline","bool",!1,!1,a,this,
!0,[{label:"true",value:!0},{label:"false",value:!1}])),this.styleList.addItem(new ControlStyleType("Text","WordWrap","bool",!1,!1,a,this,!0,[{label:"true",value:!0},{label:"false",value:!1}])),this.styleList.addItem(new ControlStyleType("Text","TextLineSpacing","number",!1,!1,a,this,0,null));if("DataListStyle"==this.styleName||"ScrollBarStyle"==this.styleName||"AlertStyle"==this.styleName||"ListContainerStyle"==this.styleName||"AlertContentListContainerStyle"==this.styleName||"AlertButtonListContainerStyle"==
this.styleName)this.styleList.addItem(new ControlStyleType("Layout","LayoutDirection","string",!1,!1,a,this,"vertical",[{label:"vertical",value:"vertical"},{label:"horizontal",value:"horizontal"}])),this.styleList.addItem(new ControlStyleType("Layout","LayoutGap","number",!1,!1,a,this,-1,null)),this.styleList.addItem(new ControlStyleType("Layout","LayoutVerticalAlign","string",!1,!1,a,this,"middle",[{label:"top",value:"top"},{label:"middle",value:"middle"},{label:"bottom",value:"bottom"}])),this.styleList.addItem(new ControlStyleType("Layout",
"LayoutHorizontalAlign","string",!1,!1,a,this,"center",[{label:"left",value:"left"},{label:"center",value:"center"},{label:"right",value:"right"}]));if("DataListStyle"==this.styleName||"PopupDataListStyle"==this.styleName||"DataGridStyle"==this.styleName)this.styleList.addItem(new ControlStyleType("Layout","ScrollBarPlacement","string",!1,!1,a,this,"right",[{label:"left",value:"left"},{label:"right",value:"right"},{label:"top",value:"top"},{label:"bottom",value:"bottom"}])),this.styleList.addItem(new ControlStyleType("Functional",
"Selectable","bool",!1,!1,a,this,!0,[{label:"true",value:!0},{label:"false",value:!1}])),this.styleList.addItem(new ControlStyleType("Functional","ScrollBarDisplay","string",!1,!1,a,this,"auto",[{label:"auto",value:"auto"},{label:"on",value:"on"},{label:"off",value:"off"}])),this.styleList.addItem(new ControlStyleType("Sub Styles","ScrollBarStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}])),this.styleList.addItem(new ControlStyleType("Sub Styles","ListItemStyle",
"class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}]));"AlertStyle"==this.styleName&&(this.styleList.addItem(new ControlStyleType("Sub Styles","AlertTitleLabelStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}])),this.styleList.addItem(new ControlStyleType("Sub Styles","AlertContentListContainerStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}])),this.styleList.addItem(new ControlStyleType("Sub Styles",
"AlertButtonListContainerStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}])),this.styleList.addItem(new ControlStyleType("Sub Styles","AlertContentTextStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}])),this.styleList.addItem(new ControlStyleType("Sub Styles","AlertButtonStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}])));"DataGridStyle"==this.styleName&&(this.styleList.addItem(new ControlStyleType("Layout",
"GridLinesPriority","string",!1,!1,a,this,"vertical",[{label:"vertical",value:"vertical"},{label:"horizontal",value:"horizontal"}])),this.styleList.addItem(new ControlStyleType("Sub Styles","HeaderStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}])),this.styleList.addItem(new ControlStyleType("Sub Styles","VerticalGridLinesStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}])),this.styleList.addItem(new ControlStyleType("Sub Styles",
"HorizontalGridLinesStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}])));-1<this.styleName.indexOf("DataGridColumn")&&(this.styleList.addItem(new ControlStyleType("Container","MinSize","number",!0,!0,a,this,100,null)),this.styleList.addItem(new ControlStyleType("Functional","HeaderText","string",!1,!1,a,this,"My Text",null)),this.styleList.addItem(new ControlStyleType("Functional","SelectionType","string",!1,!1,a,this,"row",[{label:"row",value:"row"},{label:"column",
value:"column"},{label:"cell",value:"cell"}])),this.styleList.addItem(new ControlStyleType("Functional","Selectable","bool",!1,!1,a,this,!0,[{label:"true",value:!0},{label:"false",value:!1}])),this.styleList.addItem(new ControlStyleType("Functional","Highlightable","bool",!1,!1,a,this,!0,[{label:"true",value:!0},{label:"false",value:!1}])),this.styleList.addItem(new ControlStyleType("Sub Styles","HeaderItemStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}])),
this.styleList.addItem(new ControlStyleType("Sub Styles","RowItemStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}])));"HeaderStyle"==this.styleName&&(this.styleList.addItem(new ControlStyleType("Functional","DraggableColumns","bool",!1,!1,a,this,!0,[{label:"true",value:!0},{label:"false",value:!1}])),this.styleList.addItem(new ControlStyleType("Sub Styles","ColumnDividerStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}])));
"HeaderItemStyle"==this.styleName&&(this.styleList.addItem(new ControlStyleType("Layout","SortIconGap","number",!1,!1,a,this,3,null)),this.styleList.addItem(new ControlStyleType("Layout","SortIconPlacement","string",!1,!1,a,this,"right",[{label:"left",value:"left"},{label:"right",value:"right"}])),this.styleList.addItem(new ControlStyleType("Sub Styles","SortAscIconStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}])),this.styleList.addItem(new ControlStyleType("Sub Styles",
"SortDescIconStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}])));if("ColumnDividerStyle"==this.styleName||0<=this.styleName.indexOf("SkinStyle")&&this.hasParentStyleName("ColumnDividerStyle"))this.styleList.addItem(new ControlStyleType("Rendering","DividerLineColor","color",!0,!1,a,this,"#000000",null)),this.styleList.addItem(new ControlStyleType("Rendering","DividerArrowColor","color",!0,!1,a,this,"#000000",null));"ScrollBarStyle"==this.styleName&&(this.styleList.addItem(new ControlStyleType("Functional",
"ScrollTweenDuration","number",!1,!1,a,this,180,null)),this.styleList.addItem(new ControlStyleType("Sub Styles","ButtonIncrementStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}])),this.styleList.addItem(new ControlStyleType("Sub Styles","ButtonDecrementStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}])),this.styleList.addItem(new ControlStyleType("Sub Styles","ButtonTrackStyle","class",!1,!1,a,this,StyleDefinition,
[{label:"StyleDefinition",value:StyleDefinition}])),this.styleList.addItem(new ControlStyleType("Sub Styles","ButtonTabStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}])));if("ToggleButtonStyle"==this.styleName||"RadioButtonStyle"==this.styleName||"CheckboxStyle"==this.styleName)this.styleList.addItem(new ControlStyleType("Functional","AllowDeselect","bool",!1,!1,a,this,!0,[{label:"true",value:!0},{label:"false",value:!1}])),this.styleList.addItem(new ControlStyleType("Sub Styles",
"SelectedUpSkinStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}])),this.styleList.addItem(new ControlStyleType("Sub Styles","SelectedOverSkinStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}])),this.styleList.addItem(new ControlStyleType("Sub Styles","SelectedDownSkinStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}])),this.styleList.addItem(new ControlStyleType("Sub Styles",
"SelectedDisabledSkinStyle","class",!1,!1,a,this,StyleDefinition,[{label:"StyleDefinition",value:StyleDefinition}])),this.styleList.addItem(new ControlStyleType("Text","SelectedUpTextColor","color",!1,!1,a,this,"#000000",null)),this.styleList.addItem(new ControlStyleType("Text","SelectedOverTextColor","color",!1,!1,a,this,"#000000",null)),this.styleList.addItem(new ControlStyleType("Text","SelectedDownTextColor","color",!1,!1,a,this,"#000000",null)),this.styleList.addItem(new ControlStyleType("Text",
"SelectedDisabledTextColor","color",!1,!1,a,this,"#000000",null));if("RadioButtonStyle"==this.styleName||"CheckboxStyle"==this.styleName)this.styleList.addItem(new ControlStyleType("Layout","LabelPlacement","string",!1,!1,a,this,"right",[{label:"right",value:"right"},{label:"left",value:"left"}])),this.styleList.addItem(new ControlStyleType("Layout","LabelGap","number",!1,!1,a,this,5,null));if("RadioButtonStyle"==this.styleName||"CheckboxStyle"==this.styleName||0<=this.styleName.indexOf("SkinStyle")&&
(this.hasParentStyleName("RadioButtonStyle")||this.hasParentStyleName("CheckboxStyle"))){b=.35;if("CheckboxStyle"==this.styleName||this.hasParentStyleName("CheckboxStyle"))b=.8;this.styleList.addItem(new ControlStyleType("Rendering","CheckColor","color",!1,!1,a,this,"#000000",null));this.styleList.addItem(new ControlStyleType("Rendering","CheckSize","number",!1,!1,a,this,b,null))}if("DropdownStyle"==this.styleName||"ArrowButtonStyle"==this.styleName||0<=this.styleName.indexOf("SkinStyle")&&this.hasParentStyleName("ArrowButtonStyle"))this.styleList.addItem(new ControlStyleType("Rendering",
"ArrowColor","color",!0,!1,a,this,"#000000",null)),this.styleList.addItem(new ControlStyleType("Rendering","LineColor","color",!0,!1,a,this,"#000000",null));if("ButtonIncrementStyle"==this.styleName||"ButtonDecrementStyle"==this.styleName||0<=this.styleName.indexOf("SkinStyle")&&(this.hasParentStyleName("ButtonIncrementStyle")||this.hasParentStyleName("ButtonDecrementStyle")))this.styleList.addItem(new ControlStyleType("Rendering","ArrowColor","color",!0,!1,a,this,"#000000",null)),this.styleList.addItem(new ControlStyleType("Rendering",
"ArrowDirection","string",!1,!1,a,this,"up",[{label:"up",value:"up"},{label:"down",value:"down"},{label:"left",value:"left"},{label:"right",value:"right"}]));if(a instanceof ArrowShape||a instanceof RoundedRectangleShape)this.styleList.addItem(new ControlStyleType("Rendering","CornerRadius","number",!1,!1,a,this,0,null)),this.styleList.addItem(new ControlStyleType("Rendering","CornerRadiusTopLeft","number",!0,!0,a,this,0,null)),this.styleList.addItem(new ControlStyleType("Rendering","CornerRadiusTopRight",
"number",!0,!0,a,this,0,null)),this.styleList.addItem(new ControlStyleType("Rendering","CornerRadiusBottomLeft","number",!0,!0,a,this,0,null)),this.styleList.addItem(new ControlStyleType("Rendering","CornerRadiusBottomRight","number",!0,!0,a,this,0,null));a instanceof RoundedRectangleShape&&(this.styleList.addItem(new ControlStyleType("Rendering","CornerRadiusPercent","number",!1,!1,a,this,0,null)),this.styleList.addItem(new ControlStyleType("Rendering","CornerRadiusTopLeftPercent","number",!0,!0,
a,this,0,null)),this.styleList.addItem(new ControlStyleType("Rendering","CornerRadiusTopRightPercent","number",!0,!0,a,this,0,null)),this.styleList.addItem(new ControlStyleType("Rendering","CornerRadiusBottomLeftPercent","number",!0,!0,a,this,0,null)),this.styleList.addItem(new ControlStyleType("Rendering","CornerRadiusBottomRightPercent","number",!0,!0,a,this,0,null)));a instanceof ArrowShape&&(this.styleList.addItem(new ControlStyleType("Rendering","Direction","string",!1,!1,a,this,"up",[{label:"up",
value:"up"},{label:"down",value:"down"},{label:"left",value:"left"},{label:"right",value:"right"}])),this.styleList.addItem(new ControlStyleType("Rendering","RectBaseWidth","number",!0,!0,a,this,6,null)),this.styleList.addItem(new ControlStyleType("Rendering","RectBaseHeight","number",!0,!0,a,this,6,null)),this.styleList.addItem(new ControlStyleType("Rendering","RectBasePercentWidth","number",!0,!0,a,this,50,null)),this.styleList.addItem(new ControlStyleType("Rendering","RectBasePercentHeight","number",
!0,!0,a,this,50,null)));a instanceof SolidFill&&this.styleList.addItem(new ControlStyleType("Rendering","FillColor","color",!1,!1,a,this,"#FFFF00",null));a instanceof LinearGradientFill&&(this.styleList.addItem(new ControlStyleType("Rendering","GradientDegrees","number",!1,!1,a,this,0,null)),this.styleList.addItem(new ControlStyleType("Rendering","GradientColorStops","json",!1,!1,a,this,'[[0,"#000000"],[1,"#00FFFF"]]',null)),this.styleList.addItem(new ControlStyleType("Rendering","GradientCoverage",
"string",!1,!1,a,this,"inner",[{label:"inner",value:"inner"},{label:"outer",value:"outer"}])));a=Object.create(null);for(b=0;b<this.styleList.getLength();b++)a[this.styleList.getItemAt(b).category]=!0;for(var c in a)this.styleList.addItem(new ControlStyleType(c,"",null,!1,!1,null,this,null,null));this.styleList.sort()}};function CloseButtonSkinElement(){CloseButtonSkinElement.base.prototype.constructor.call(this)}CloseButtonSkinElement.prototype=Object.create(CanvasElement.prototype);
CloseButtonSkinElement.prototype.constructor=CloseButtonSkinElement;CloseButtonSkinElement.base=CanvasElement;CloseButtonSkinElement.prototype._doRender=function(){CloseButtonSkinElement.base.prototype._doRender.call(this);var a=this._getGraphicsCtx(),b=this._x,c=this._y,d=this._width,e=this._height,f;f="up"==this.getStyle("SkinState")?"#444444":"#222222";a.beginPath();a.moveTo(b+4.5,c+4.5);a.lineTo(b+d-4.5,c+e-4.5);a.moveTo(b+d-4.5,c+4.5);a.lineTo(b+4.5,c+e-4.5);a.strokeStyle=f;a.lineWidth=2;a.stroke()};
function AddStyleDataRenderer(){AddStyleDataRenderer.base.prototype.constructor.call(this);this._divider=new CanvasElement;this._divider.setStyle("BackgroundFill","#000000");this._checkboxSelected=new CheckboxElement;this._addChild(this._divider);this._addChild(this._checkboxSelected);var a=this;this._onAddStyleDataRendererClickInstance=function(b){a._onAddStyleDataRendererClick(b)};this.addEventListener("click",this._onAddStyleDataRendererClickInstance)}AddStyleDataRenderer.prototype=Object.create(DataRendererLabelElement.prototype);
AddStyleDataRenderer.prototype.constructor=AddStyleDataRenderer;AddStyleDataRenderer.base=DataRendererLabelElement;AddStyleDataRenderer.prototype._onAddStyleDataRendererClick=function(a){a.getTarget()!=this._checkboxSelected&&""!=this._itemData.styleName&&this._listData._parentList.dispatchEvent(new ElementEvent("changed",!1))};
AddStyleDataRenderer.prototype._setListData=function(a,b){AddStyleDataRenderer.base.prototype._setListData.call(this,a,b);""==this._itemData.styleName?(this.setStyle("PaddingTop",2),this.setStyle("PaddingBottom",1),this.setStyle("PaddingLeft",4),this.setStyle("PaddingRight",10),this.setStyle("TextStyle","bold"),this.setStyle("Selectable",!1),this._divider.setStyle("Visible",!0),this._checkboxSelected.setStyle("Visible",!1)):(this.setStyle("PaddingTop",4),this.setStyle("PaddingBottom",4),this.setStyle("PaddingLeft",
14),this.setStyle("PaddingRight",10),this.setStyle("TextStyle","normal"),this.setStyle("Selectable",!0),this._divider.setStyle("Visible",!1),this._checkboxSelected.setStyle("Visible",!0),this._itemData.styleName in this._itemData.styleDefinition._styleMap?this._checkboxSelected.setSelected(!0):this._checkboxSelected.setSelected(!1))};
AddStyleDataRenderer.prototype._doLayout=function(a){AddStyleDataRenderer.base.prototype._doLayout.call(this,a);var b=a.getX(),c=a.getY(),d=a.getWidth();a=a.getHeight();this._divider._setActualPosition(b,this._height-1);this._divider._setActualSize(d,1);this._checkboxSelected._setActualSize(this._labelElement._height,this._labelElement._height);this._checkboxSelected._setActualPosition(b+d-this._checkboxSelected._width,Math.round(c+a/2-this._checkboxSelected._height/2))};
