//MIT License
//
//Copyright (c) 2017-2018 SENSORMATIC ELECTRONICS LLC, NATHAN E NELSON
//
//Permission is hereby granted, free of charge, to any person obtaining a copy
//of this software and associated documentation files (the "Software"), to deal
//in the Software without restriction, including without limitation the rights
//to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//copies of the Software, and to permit persons to whom the Software is
//furnished to do so, subject to the following conditions:
//
//The above copyright notice and this permission notice shall be included in all
//copies or substantial portions of the Software.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//SOFTWARE.

var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,c,d){var b=this.length||0;0>c&&(c=Math.max(0,b+c));if(null==d||d>b)d=b;d=Number(d);0>d&&(d=Math.max(0,b+d));for(c=Number(c||0);c<d;c++)this[c]=a;return this}},"es6-impl","es3");
var applicationStyles=new StyleDefinition;applicationStyles.setStyle("BackgroundColor","#444444");applicationStyles.setStyle("TextLinePaddingTop",2);applicationStyles.setStyle("TextLinePaddingBottom",2);var ButtonDownSkinStyle=new StyleDefinition;ButtonDownSkinStyle.setStyle("BackgroundColor","#BEBEBE");var ButtonOverSkinStyle=new StyleDefinition;ButtonOverSkinStyle.setStyle("BackgroundColor","#AFAFAF");var ButtonUpSkinStyle=new StyleDefinition;ButtonUpSkinStyle.setStyle("BackgroundColor","#9F9F9F");
var ButtonDisabledSkinStyle=new StyleDefinition;ButtonDisabledSkinStyle.setStyle("BackgroundColor","#777777");var buttonBackgroundShapeStyle=new RoundedRectangleShape;buttonBackgroundShapeStyle.setStyle("CornerRadius",5);var buttonBackgroundStyle=new StyleDefinition;buttonBackgroundStyle.setStyle("DownSkinStyle",ButtonDownSkinStyle);buttonBackgroundStyle.setStyle("OverSkinStyle",ButtonOverSkinStyle);buttonBackgroundStyle.setStyle("UpSkinStyle",ButtonUpSkinStyle);
buttonBackgroundStyle.setStyle("SelectedDownSkinStyle",ButtonDownSkinStyle);buttonBackgroundStyle.setStyle("SelectedOverSkinStyle",ButtonOverSkinStyle);buttonBackgroundStyle.setStyle("SelectedUpSkinStyle",ButtonUpSkinStyle);buttonBackgroundStyle.setStyle("DisabledSkinStyle",ButtonDisabledSkinStyle);buttonBackgroundStyle.setStyle("BorderType",null);buttonBackgroundStyle.setStyle("AutoGradientType",null);buttonBackgroundStyle.setStyle("BackgroundShape",buttonBackgroundShapeStyle);
var textCreditsStyle=new StyleDefinition;textCreditsStyle.setStyle("TextFont","Arial");textCreditsStyle.setStyle("TextStyle","bold");textCreditsStyle.setStyle("TextColor","#DDDDDD");textCreditsStyle.setStyle("TextSize",14);var textLinkStyle=new StyleDefinition;textLinkStyle.setStyle("TextDecoration","underline");textLinkStyle.setStyle("Cursor","pointer");var buttonPlayStyle=new StyleDefinition;buttonPlayStyle.setStyle("Padding",5);buttonPlayStyle.setStyle("PaddingLeft",30);
buttonPlayStyle.setStyle("PaddingRight",30);buttonPlayStyle.setStyle("TextFont","Audiowide");buttonPlayStyle.setStyle("TextSize",22);buttonPlayStyle.setStyle("TextStyle","bold");buttonPlayStyle.setStyle("Text","PLAY");var buttonMenuStyle=new StyleDefinition;buttonMenuStyle.setStyle("TextFont","Audiowide");buttonMenuStyle.setStyle("TextSize",22);buttonMenuStyle.setStyle("TextStyle","bold");buttonMenuStyle.setStyle("Text","MENU");var labelSelectStyle=new StyleDefinition;
labelSelectStyle.setStyle("TextSize",22);labelSelectStyle.setStyle("TextStyle","bold");labelSelectStyle.setStyle("TextFont","Audiowide");labelSelectStyle.setStyle("TextColor","#DDDDDD");var labelControlsStyle=new StyleDefinition;labelControlsStyle.setStyle("TextSize",17);labelControlsStyle.setStyle("TextFont","Audiowide");labelControlsStyle.setStyle("TextColor","#DDDDDD");labelControlsStyle.setStyle("TextStyle","bold");labelControlsStyle.setStyle("TextHorizontalAlign","center");
labelControlsStyle.setStyle("PercentWidth",100);labelControlsStyle.setStyle("TextHorizontalAlign","left");var labelControlsValueStyle=new StyleDefinition;labelControlsValueStyle.setStyle("TextSize",17);labelControlsValueStyle.setStyle("TextFont","Audiowide");labelControlsValueStyle.setStyle("TextColor","#DDDDDD");labelControlsValueStyle.setStyle("TextHorizontalAlign","center");var labelControlsValueCol1Style=new StyleDefinition;labelControlsValueCol1Style.setStyle("Width",100);
var labelControlsValueCol2Style=new StyleDefinition;labelControlsValueCol2Style.setStyle("Width",150);var labelControlsValueCol3Style=new StyleDefinition;labelControlsValueCol3Style.setStyle("Width",120);labelControlsValueCol3Style.setStyle("TextHorizontalAlign","right");var labelControlsDividerStyle=new StyleDefinition;labelControlsDividerStyle.setStyle("PercentHeight",70);labelControlsDividerStyle.setStyle("Width",1);labelControlsDividerStyle.setStyle("BackgroundColor","#DDDDDD");
var labelPlayFieldStyle=new StyleDefinition;labelPlayFieldStyle.setStyle("TextStyle","bold");labelPlayFieldStyle.setStyle("TextFont","Audiowide");labelPlayFieldStyle.setStyle("TextColor","#DDDDDD");var labelPlayFieldStartCountSizeStyle=new StyleDefinition;labelPlayFieldStartCountSizeStyle.setStyle("TextSize",80);var labelPlayFieldExLargeSizeStyle=new StyleDefinition;labelPlayFieldExLargeSizeStyle.setStyle("TextSize",36);var labelPlayFieldLargeSizeStyle=new StyleDefinition;
labelPlayFieldLargeSizeStyle.setStyle("TextSize",24);var labelPlayFieldSmallSizeStyle=new StyleDefinition;labelPlayFieldSmallSizeStyle.setStyle("TextSize",20);var scoreControlsDividerStyle=new StyleDefinition;scoreControlsDividerStyle.setStyle("PercentWidth",80);scoreControlsDividerStyle.setStyle("Height",1);scoreControlsDividerStyle.setStyle("BackgroundColor","#DDDDDD");var playFieldOuterContainerBackgroundShapeStyle=new RoundedRectangleShape;
playFieldOuterContainerBackgroundShapeStyle.setStyle("CornerRadius",5);var playFieldOuterContainerStyle=new StyleDefinition;playFieldOuterContainerStyle.setStyle("BackgroundColor","#DDDDDD");playFieldOuterContainerStyle.setStyle("BackgroundShape",playFieldOuterContainerBackgroundShapeStyle);var playFieldInnerContainerStyle=new StyleDefinition;playFieldInnerContainerStyle.setStyle("BackgroundColor","#202020");playFieldInnerContainerStyle.setStyle("Top",3);
playFieldInnerContainerStyle.setStyle("Bottom",3);playFieldInnerContainerStyle.setStyle("Left",3);playFieldInnerContainerStyle.setStyle("Right",3);var sound_countdownbeep=new Audio(["Sounds/37732__longhairman__1khz-1ds-peep.mp3"]),sound_countdownLicenseData={name:"1khz-1ds-peep",link:"https://freesound.org/people/Longhairman/sounds/37732/",author:"Longhairman",authorLink:"https://freesound.org/people/Longhairman/",license:"CC0 1.0",licenseLink:"https://creativecommons.org/publicdomain/zero/1.0/"};
sound_countdownbeep.volume=.35;
var sound_rotate=new Audio(["Sounds/187024__lloydevans09__jump2.mp3"]),sound_rotateLicenseData={name:"jump2",link:"https://freesound.org/people/LloydEvans09/sounds/187024/",author:"LloydEvans09",authorLink:"https://freesound.org/people/LloydEvans09/",license:"CC BY 3.0",licenseLink:"https://creativecommons.org/licenses/by/3.0/"},sound_lineComplete=new Audio(["Sounds/109662__grunz__success.mp3"]),sound_lineCompleteLicenseData={name:"success",link:"https://freesound.org/people/grunz/sounds/109662/",author:"grunz",
authorLink:"https://freesound.org/people/grunz/",license:"CC BY 3.0",licenseLink:"https://creativecommons.org/licenses/by/3.0/"},sound_levelUp=new Audio(["Sounds/320777__rhodesmas__action-01.mp3"]),sound_levelUpLicenseData={name:"action-01",link:"https://freesound.org/people/rhodesmas/sounds/320777/",author:"rhodesmas",authorLink:"https://freesound.org/people/rhodesmas/",license:"CC BY 3.0",licenseLink:"https://creativecommons.org/licenses/by/3.0/"},sound_music=new Audio(["Sounds/382931__frankum__vintage-techno-house-loop-110bpm.mp3"]),
sound_musicLicenseData={name:"vintage-techno-house-loop-110bpm",link:"https://freesound.org/people/frankum/sounds/382931/",author:"frankum",authorLink:"https://freesound.org/people/frankum/",license:"CC BY 3.0",licenseLink:"https://creativecommons.org/licenses/by/3.0/"};sound_music.loop=!0;var tetriStack=null;function init(){tetriStack=new TetriStackApplication;tetriStack.setCanvas(document.getElementById("canvasTetriStack"))}
function TetriStackApplication(){TetriStackApplication.base.prototype.constructor.call(this);this.setStyleDefinitions(applicationStyles);this._rootContainer=new ListContainerElement;this._rootContainer.setStyle("PercentWidth",100);this._rootContainer.setStyle("PercentHeight",100);this._contentContainer=new AnchorContainerElement;this._contentContainer.setStyle("PercentWidth",100);this._contentContainer.setStyle("PercentHeight",100);this._menuView=new ListContainerElement;this._menuView.setStyle("LayoutHorizontalAlign",
"center");this._menuView.setStyle("LayoutVerticalAlign","middle");this._menuView.setStyle("LayoutGap",10);this._menuView.setStyle("PercentWidth",100);this._menuView.setStyle("PercentHeight",100);this._titleContainer=new AnchorContainerElement;this._labelSelectLevel=new LabelElement;this._labelSelectLevel.setStyleDefinitions(labelSelectStyle);this._labelSelectLevel.setStyle("Text","Start At Level");this._labelSelectLevel.setStyle("PaddingTop",20);this._levelSelectContainer=new ListContainerElement;
this._levelSelectContainer.setStyle("LayoutDirection","horizontal");this._levelSelectContainer.setStyle("LayoutVerticalAlign","middle");this._levelSelectContainer.setStyle("LayoutGap",30);this._levelSelectContainer.setStyle("PaddingBottom",20);var a=new ArrowShape;a.setStyle("Direction","left");this._buttonLowerLevel=new ButtonElement;this._buttonLowerLevel.setStyle("Width",25);this._buttonLowerLevel.setStyle("Height",25);this._buttonLowerLevel.setStyle("Enabled",!1);this._buttonLowerLevel.setStyle("BackgroundShape",
a);this._buttonLowerLevel.setStyleDefinitions([buttonBackgroundStyle]);this._labelSelectedLevel=new LabelElement;this._labelSelectedLevel.setStyle("Text","1");this._labelSelectedLevel.setStyle("Width",35);this._labelSelectedLevel.setStyle("TextHorizontalAlign","center");this._labelSelectedLevel.setStyleDefinitions(labelSelectStyle);a=new ArrowShape;a.setStyle("Direction","right");this._buttonHigherLevel=new ButtonElement;this._buttonHigherLevel.setStyle("Width",25);this._buttonHigherLevel.setStyle("Height",
25);this._buttonHigherLevel.setStyle("BackgroundShape",a);this._buttonHigherLevel.setStyleDefinitions([buttonBackgroundStyle]);this._levelSelectContainer.addElement(this._buttonLowerLevel);this._levelSelectContainer.addElement(this._labelSelectedLevel);this._levelSelectContainer.addElement(this._buttonHigherLevel);this._audioSelectContainer=new TetriAudioSelectSettings;this._audioSelectContainer.setStyle("PaddingBottom",25);this._buttonPlay=new ButtonElement;this._buttonPlay.setStyleDefinitions([buttonBackgroundStyle,
buttonPlayStyle]);this._controlsContainer=new ListContainerElement;this._controlsContainer.setStyle("PaddingTop",25);this._controlsContainer.setStyle("LayoutGap",5);this._controlsContainer.setStyle("LayoutHorizontalAlign","center");this._controlsDivider=new CanvasElement;this._controlsDivider.setStyle("Height",1);this._controlsDivider.setStyle("Width",520);this._controlsDivider.setStyle("BackgroundColor","#DDDDDD");this._controlMoveLeftContainer=new ListContainerElement;this._controlMoveLeftContainer.setStyle("LayoutDirection",
"horizontal");this._controlMoveLeftContainer.setStyle("LayoutVerticalAlign","middle");this._controlMoveLeftContainer.setStyle("PercentWidth",100);this._labelControlMoveLeft=new LabelElement;this._labelControlMoveLeft.setStyle("Text","Move Left:");this._labelControlMoveLeft.setStyleDefinitions(labelControlsStyle);this._labelControlMoveLeftKey1=new LabelElement;this._labelControlMoveLeftKey1.setStyle("Text","A");this._labelControlMoveLeftKey1.setStyleDefinitions([labelControlsValueStyle,labelControlsValueCol1Style]);
this._labelControlMoveLeftDivider1=new CanvasElement;this._labelControlMoveLeftDivider1.setStyleDefinitions(labelControlsDividerStyle);this._labelControlMoveLeftKey2=new LabelElement;this._labelControlMoveLeftKey2.setStyle("Text","Arrow Left");this._labelControlMoveLeftKey2.setStyleDefinitions([labelControlsValueStyle,labelControlsValueCol2Style]);this._labelControlMoveLeftDivider2=new CanvasElement;this._labelControlMoveLeftDivider2.setStyleDefinitions(labelControlsDividerStyle);this._labelControlMoveLeftKey3=
new LabelElement;this._labelControlMoveLeftKey3.setStyle("Text","NumPad 4");this._labelControlMoveLeftKey3.setStyleDefinitions([labelControlsValueStyle,labelControlsValueCol3Style]);this._controlMoveLeftContainer.addElement(this._labelControlMoveLeft);this._controlMoveLeftContainer.addElement(this._labelControlMoveLeftKey1);this._controlMoveLeftContainer.addElement(this._labelControlMoveLeftDivider1);this._controlMoveLeftContainer.addElement(this._labelControlMoveLeftKey2);this._controlMoveLeftContainer.addElement(this._labelControlMoveLeftDivider2);
this._controlMoveLeftContainer.addElement(this._labelControlMoveLeftKey3);this._controlMoveRightContainer=new ListContainerElement;this._controlMoveRightContainer.setStyle("LayoutDirection","horizontal");this._controlMoveRightContainer.setStyle("LayoutVerticalAlign","middle");this._controlMoveRightContainer.setStyle("PercentWidth",100);this._labelControlMoveRight=new LabelElement;this._labelControlMoveRight.setStyle("Text","Move Right:");this._labelControlMoveRight.setStyleDefinitions(labelControlsStyle);
this._labelControlMoveRightKey1=new LabelElement;this._labelControlMoveRightKey1.setStyle("Text","D");this._labelControlMoveRightKey1.setStyleDefinitions([labelControlsValueStyle,labelControlsValueCol1Style]);this._labelControlMoveRightDivider1=new CanvasElement;this._labelControlMoveRightDivider1.setStyleDefinitions(labelControlsDividerStyle);this._labelControlMoveRightKey2=new LabelElement;this._labelControlMoveRightKey2.setStyle("Text","Arrow Right");this._labelControlMoveRightKey2.setStyleDefinitions([labelControlsValueStyle,
labelControlsValueCol2Style]);this._labelControlMoveRightDivider2=new CanvasElement;this._labelControlMoveRightDivider2.setStyleDefinitions(labelControlsDividerStyle);this._labelControlMoveRightKey3=new LabelElement;this._labelControlMoveRightKey3.setStyle("Text","NumPad 6");this._labelControlMoveRightKey3.setStyleDefinitions([labelControlsValueStyle,labelControlsValueCol3Style]);this._controlMoveRightContainer.addElement(this._labelControlMoveRight);this._controlMoveRightContainer.addElement(this._labelControlMoveRightKey1);
this._controlMoveRightContainer.addElement(this._labelControlMoveRightDivider1);this._controlMoveRightContainer.addElement(this._labelControlMoveRightKey2);this._controlMoveRightContainer.addElement(this._labelControlMoveRightDivider2);this._controlMoveRightContainer.addElement(this._labelControlMoveRightKey3);this._controlSoftDropContainer=new ListContainerElement;this._controlSoftDropContainer.setStyle("LayoutDirection","horizontal");this._controlSoftDropContainer.setStyle("LayoutVerticalAlign",
"middle");this._controlSoftDropContainer.setStyle("PercentWidth",100);this._labelControlSoftDrop=new LabelElement;this._labelControlSoftDrop.setStyle("Text","Soft Drop:");this._labelControlSoftDrop.setStyleDefinitions(labelControlsStyle);this._labelControlSoftDropKey1=new LabelElement;this._labelControlSoftDropKey1.setStyle("Text","S");this._labelControlSoftDropKey1.setStyleDefinitions([labelControlsValueStyle,labelControlsValueCol1Style]);this._labelControlSoftDropDivider1=new CanvasElement;this._labelControlSoftDropDivider1.setStyleDefinitions(labelControlsDividerStyle);
this._labelControlSoftDropKey2=new LabelElement;this._labelControlSoftDropKey2.setStyle("Text","Arrow Down");this._labelControlSoftDropKey2.setStyleDefinitions([labelControlsValueStyle,labelControlsValueCol2Style]);this._labelControlSoftDropDivider2=new CanvasElement;this._labelControlSoftDropDivider2.setStyleDefinitions(labelControlsDividerStyle);this._labelControlSoftDropKey3=new LabelElement;this._labelControlSoftDropKey3.setStyle("Text","NumPad 5");this._labelControlSoftDropKey3.setStyleDefinitions([labelControlsValueStyle,
labelControlsValueCol3Style]);this._controlSoftDropContainer.addElement(this._labelControlSoftDrop);this._controlSoftDropContainer.addElement(this._labelControlSoftDropKey1);this._controlSoftDropContainer.addElement(this._labelControlSoftDropDivider1);this._controlSoftDropContainer.addElement(this._labelControlSoftDropKey2);this._controlSoftDropContainer.addElement(this._labelControlSoftDropDivider2);this._controlSoftDropContainer.addElement(this._labelControlSoftDropKey3);this._controlHardDropContainer=
new ListContainerElement;this._controlHardDropContainer.setStyle("LayoutDirection","horizontal");this._controlHardDropContainer.setStyle("LayoutVerticalAlign","middle");this._controlHardDropContainer.setStyle("PercentWidth",100);this._labelControlHardDrop=new LabelElement;this._labelControlHardDrop.setStyle("Text","Hard Drop:");this._labelControlHardDrop.setStyleDefinitions(labelControlsStyle);this._labelControlHardDropKey1=new LabelElement;this._labelControlHardDropKey1.setStyle("Text","W");this._labelControlHardDropKey1.setStyleDefinitions([labelControlsValueStyle,
labelControlsValueCol1Style]);this._labelControlHardDropDivider1=new CanvasElement;this._labelControlHardDropDivider1.setStyleDefinitions(labelControlsDividerStyle);this._labelControlHardDropKey2=new LabelElement;this._labelControlHardDropKey2.setStyle("Text","Arrow Up");this._labelControlHardDropKey2.setStyleDefinitions([labelControlsValueStyle,labelControlsValueCol2Style]);this._labelControlHardDropDivider2=new CanvasElement;this._labelControlHardDropDivider2.setStyleDefinitions(labelControlsDividerStyle);
this._labelControlHardDropKey3=new LabelElement;this._labelControlHardDropKey3.setStyle("Text","NumPad 8");this._labelControlHardDropKey3.setStyleDefinitions([labelControlsValueStyle,labelControlsValueCol3Style]);this._controlHardDropContainer.addElement(this._labelControlHardDrop);this._controlHardDropContainer.addElement(this._labelControlHardDropKey1);this._controlHardDropContainer.addElement(this._labelControlHardDropDivider1);this._controlHardDropContainer.addElement(this._labelControlHardDropKey2);
this._controlHardDropContainer.addElement(this._labelControlHardDropDivider2);this._controlHardDropContainer.addElement(this._labelControlHardDropKey3);this._controlRotateLeftContainer=new ListContainerElement;this._controlRotateLeftContainer.setStyle("LayoutDirection","horizontal");this._controlRotateLeftContainer.setStyle("LayoutVerticalAlign","middle");this._controlRotateLeftContainer.setStyle("PercentWidth",100);this._labelControlRotateLeft=new LabelElement;this._labelControlRotateLeft.setStyle("Text",
"Rotate Left:");this._labelControlRotateLeft.setStyleDefinitions(labelControlsStyle);this._labelControlRotateLeftKey1=new LabelElement;this._labelControlRotateLeftKey1.setStyle("Text","Q");this._labelControlRotateLeftKey1.setStyleDefinitions([labelControlsValueStyle,labelControlsValueCol1Style]);this._labelControlRotateLeftDivider1=new CanvasElement;this._labelControlRotateLeftDivider1.setStyleDefinitions(labelControlsDividerStyle);this._labelControlRotateLeftKey2=new LabelElement;this._labelControlRotateLeftKey2.setStyle("Text",
"J");this._labelControlRotateLeftKey2.setStyleDefinitions([labelControlsValueStyle,labelControlsValueCol2Style]);this._labelControlRotateLeftDivider2=new CanvasElement;this._labelControlRotateLeftDivider2.setStyleDefinitions(labelControlsDividerStyle);this._labelControlRotateLeftKey3=new LabelElement;this._labelControlRotateLeftKey3.setStyle("Text","NumPad 7");this._labelControlRotateLeftKey3.setStyleDefinitions([labelControlsValueStyle,labelControlsValueCol3Style]);this._controlRotateLeftContainer.addElement(this._labelControlRotateLeft);
this._controlRotateLeftContainer.addElement(this._labelControlRotateLeftKey1);this._controlRotateLeftContainer.addElement(this._labelControlRotateLeftDivider1);this._controlRotateLeftContainer.addElement(this._labelControlRotateLeftKey2);this._controlRotateLeftContainer.addElement(this._labelControlRotateLeftDivider2);this._controlRotateLeftContainer.addElement(this._labelControlRotateLeftKey3);this._controlRotateRightContainer=new ListContainerElement;this._controlRotateRightContainer.setStyle("LayoutDirection",
"horizontal");this._controlRotateRightContainer.setStyle("LayoutVerticalAlign","middle");this._controlRotateRightContainer.setStyle("PercentWidth",100);this._labelControlRotateRight=new LabelElement;this._labelControlRotateRight.setStyle("Text","Rotate Right:");this._labelControlRotateRight.setStyleDefinitions(labelControlsStyle);this._labelControlRotateRightKey1=new LabelElement;this._labelControlRotateRightKey1.setStyle("Text","E");this._labelControlRotateRightKey1.setStyleDefinitions([labelControlsValueStyle,
labelControlsValueCol1Style]);this._labelControlRotateRightDivider1=new CanvasElement;this._labelControlRotateRightDivider1.setStyleDefinitions(labelControlsDividerStyle);this._labelControlRotateRightKey2=new LabelElement;this._labelControlRotateRightKey2.setStyle("Text","L");this._labelControlRotateRightKey2.setStyleDefinitions([labelControlsValueStyle,labelControlsValueCol2Style]);this._labelControlRotateRightDivider2=new CanvasElement;this._labelControlRotateRightDivider2.setStyleDefinitions(labelControlsDividerStyle);
this._labelControlRotateRightKey3=new LabelElement;this._labelControlRotateRightKey3.setStyle("Text","NumPad 9");this._labelControlRotateRightKey3.setStyleDefinitions([labelControlsValueStyle,labelControlsValueCol3Style]);this._controlRotateRightContainer.addElement(this._labelControlRotateRight);this._controlRotateRightContainer.addElement(this._labelControlRotateRightKey1);this._controlRotateRightContainer.addElement(this._labelControlRotateRightDivider1);this._controlRotateRightContainer.addElement(this._labelControlRotateRightKey2);
this._controlRotateRightContainer.addElement(this._labelControlRotateRightDivider2);this._controlRotateRightContainer.addElement(this._labelControlRotateRightKey3);this._controlHoldContainer=new ListContainerElement;this._controlHoldContainer.setStyle("LayoutDirection","horizontal");this._controlHoldContainer.setStyle("LayoutVerticalAlign","middle");this._controlHoldContainer.setStyle("PercentWidth",100);this._labelControlHold=new LabelElement;this._labelControlHold.setStyle("Text","Hold:");this._labelControlHold.setStyleDefinitions(labelControlsStyle);
this._labelControlHoldKey1=new LabelElement;this._labelControlHoldKey1.setStyle("Text","Space");this._labelControlHoldKey1.setStyleDefinitions([labelControlsValueStyle,labelControlsValueCol1Style]);this._labelControlHoldDivider1=new CanvasElement;this._labelControlHoldDivider1.setStyleDefinitions(labelControlsDividerStyle);this._labelControlHoldKey2=new LabelElement;this._labelControlHoldKey2.setStyle("Text","K");this._labelControlHoldKey2.setStyleDefinitions([labelControlsValueStyle,labelControlsValueCol2Style]);
this._labelControlHoldDivider2=new CanvasElement;this._labelControlHoldDivider2.setStyleDefinitions(labelControlsDividerStyle);this._labelControlHoldKey3=new LabelElement;this._labelControlHoldKey3.setStyle("Text","NumPad 0");this._labelControlHoldKey3.setStyleDefinitions([labelControlsValueStyle,labelControlsValueCol3Style]);this._controlHoldContainer.addElement(this._labelControlHold);this._controlHoldContainer.addElement(this._labelControlHoldKey1);this._controlHoldContainer.addElement(this._labelControlHoldDivider1);
this._controlHoldContainer.addElement(this._labelControlHoldKey2);this._controlHoldContainer.addElement(this._labelControlHoldDivider2);this._controlHoldContainer.addElement(this._labelControlHoldKey3);this._controlsContainer.addElement(this._controlsDivider);this._controlsContainer.addElement(this._controlMoveLeftContainer);this._controlsContainer.addElement(this._controlMoveRightContainer);this._controlsContainer.addElement(this._controlSoftDropContainer);this._controlsContainer.addElement(this._controlHardDropContainer);
this._controlsContainer.addElement(this._controlRotateLeftContainer);this._controlsContainer.addElement(this._controlRotateRightContainer);this._controlsContainer.addElement(this._controlHoldContainer);this._menuViewControlsCreditsSpacer=new CanvasElement;this._menuViewControlsCreditsSpacer.setStyle("Height",10);this._labelCredits=new LabelElement;this._labelCredits.setStyleDefinitions([textCreditsStyle,textLinkStyle]);this._labelCredits.setStyle("Text","View Credits");this._menuView.addElement(this._titleContainer);
this._menuView.addElement(this._labelSelectLevel);this._menuView.addElement(this._levelSelectContainer);this._menuView.addElement(this._audioSelectContainer);this._menuView.addElement(this._buttonPlay);this._menuView.addElement(this._controlsContainer);this._menuView.addElement(this._menuViewControlsCreditsSpacer);this._menuView.addElement(this._labelCredits);this._gameView=new ListContainerElement;this._gameView.setStyle("LayoutHorizontalAlign","center");this._gameView.setStyle("LayoutVerticalAlign",
"middle");this._gameView.setStyle("PercentWidth",100);this._gameView.setStyle("PercentHeight",100);this._gameView.setStyle("Visible",!1);this._playField=new TetriPlayField;this._gameView.addElement(this._playField);this._creditsView=new ListContainerElement;this._creditsView.setStyle("LayoutHorizontalAlign","center");this._creditsView.setStyle("LayoutVerticalAlign","middle");this._creditsView.setStyle("PercentWidth",100);this._creditsView.setStyle("PercentHeight",100);this._creditsView.setStyle("Visible",
!1);this._creditsView.setStyle("LayoutGap",30);this._creditsProgrammingContainer=new ListContainerElement;this._creditsProgrammingContainer.setStyle("LayoutGap",2);this._creditsProgrammingContainer.setStyle("LayoutHorizontalAlign","center");this._creditsProgrammingContainer.setStyle("LayoutVerticalAlign","middle");this._labelCreditsProgramming=new LabelElement;this._labelCreditsProgramming.setStyleDefinitions([labelPlayFieldStyle,labelPlayFieldSmallSizeStyle]);this._labelCreditsProgramming.setStyle("Text",
"PROGRAMMING");this._creditsProgrammingDivider=new CanvasElement;this._creditsProgrammingDivider.setStyleDefinitions(scoreControlsDividerStyle);this._programmingCredit1=new LabelElement;this._programmingCredit1.setStyleDefinitions([textCreditsStyle]);this._programmingCredit1.setStyle("Text","Nathan E Nelson");this._creditsProgrammingContainer.addElement(this._labelCreditsProgramming);this._creditsProgrammingContainer.addElement(this._creditsProgrammingDivider);this._creditsProgrammingContainer.addElement(this._programmingCredit1);
this._creditsDesignTestingContainer=new ListContainerElement;this._creditsDesignTestingContainer.setStyle("LayoutGap",2);this._creditsDesignTestingContainer.setStyle("LayoutHorizontalAlign","center");this._creditsDesignTestingContainer.setStyle("LayoutVerticalAlign","middle");this._labelDesignTesting=new LabelElement;this._labelDesignTesting.setStyleDefinitions([labelPlayFieldStyle,labelPlayFieldSmallSizeStyle]);this._labelDesignTesting.setStyle("Text","DESIGN & TESTING");this._creditsDesignTestingDivider=
new CanvasElement;this._creditsDesignTestingDivider.setStyleDefinitions(scoreControlsDividerStyle);this._labelDesignTestingCredit1=new LabelElement;this._labelDesignTestingCredit1.setStyleDefinitions([textCreditsStyle]);this._labelDesignTestingCredit1.setStyle("Text","Nathan E Nelson");this._labelDesignTestingCredit2=new LabelElement;this._labelDesignTestingCredit2.setStyleDefinitions([textCreditsStyle]);this._labelDesignTestingCredit2.setStyle("Text","Barbie L Spinner");this._labelDesignTestingCredit3=
new LabelElement;this._labelDesignTestingCredit3.setStyleDefinitions([textCreditsStyle]);this._labelDesignTestingCredit3.setStyle("Text","Xylomax");this._creditsDesignTestingContainer.addElement(this._labelDesignTesting);this._creditsDesignTestingContainer.addElement(this._creditsDesignTestingDivider);this._creditsDesignTestingContainer.addElement(this._labelDesignTestingCredit1);this._creditsDesignTestingContainer.addElement(this._labelDesignTestingCredit2);this._creditsDesignTestingContainer.addElement(this._labelDesignTestingCredit3);
this._creditsSoundContainer=new ListContainerElement;this._creditsSoundContainer.setStyle("LayoutGap",5);this._creditsSoundContainer.setStyle("LayoutHorizontalAlign","center");this._creditsSoundContainer.setStyle("LayoutVerticalAlign","middle");this._labelCreditsSound=new LabelElement;this._labelCreditsSound.setStyleDefinitions([labelPlayFieldStyle,labelPlayFieldSmallSizeStyle]);this._labelCreditsSound.setStyle("Text","SOUNDS");this._creditsSoundDivider=new CanvasElement;this._creditsSoundDivider.setStyleDefinitions(scoreControlsDividerStyle);
this._sound1Credit=new CCAttributeLinks;this._sound1Credit.setLicenseData(sound_countdownLicenseData);this._sound2Credit=new CCAttributeLinks;this._sound2Credit.setLicenseData(sound_rotateLicenseData);this._sound3Credit=new CCAttributeLinks;this._sound3Credit.setLicenseData(sound_lineCompleteLicenseData);this._sound4Credit=new CCAttributeLinks;this._sound4Credit.setLicenseData(sound_levelUpLicenseData);this._sound5Credit=new CCAttributeLinks;this._sound5Credit.setLicenseData(sound_musicLicenseData);
this._creditsSoundContainer.addElement(this._labelCreditsSound);this._creditsSoundContainer.addElement(this._creditsSoundDivider);this._creditsSoundContainer.addElement(this._sound1Credit);this._creditsSoundContainer.addElement(this._sound2Credit);this._creditsSoundContainer.addElement(this._sound3Credit);this._creditsSoundContainer.addElement(this._sound4Credit);this._creditsSoundContainer.addElement(this._sound5Credit);this._creditsNothingContainer=new ListContainerElement;this._creditsNothingContainer.setStyle("LayoutGap",
2);this._creditsNothingContainer.setStyle("LayoutHorizontalAlign","center");this._creditsNothingContainer.setStyle("LayoutVerticalAlign","middle");this._labelCreditsNothing=new LabelElement;this._labelCreditsNothing.setStyleDefinitions([labelPlayFieldStyle,labelPlayFieldSmallSizeStyle]);this._labelCreditsNothing.setStyle("Text","NO HELP AT ALL");this._creditsNothingDivider=new CanvasElement;this._creditsNothingDivider.setStyleDefinitions(scoreControlsDividerStyle);this._nothingCredit1=new LabelElement;
this._nothingCredit1.setStyleDefinitions([textCreditsStyle]);this._nothingCredit1.setStyle("Text","David E Snyder");this._creditsNothingContainer.addElement(this._labelCreditsNothing);this._creditsNothingContainer.addElement(this._creditsNothingDivider);this._creditsNothingContainer.addElement(this._nothingCredit1);this._buttonCreditsDone=new ButtonElement;this._buttonCreditsDone.setStyleDefinitions([buttonBackgroundStyle,buttonPlayStyle]);this._buttonCreditsDone.setStyle("Text","DONE");this._creditsView.addElement(this._creditsProgrammingContainer);
this._creditsView.addElement(this._creditsDesignTestingContainer);this._creditsView.addElement(this._creditsSoundContainer);this._creditsView.addElement(this._creditsNothingContainer);this._creditsView.addElement(this._buttonCreditsDone);this._contentContainer.addElement(this._menuView);this._contentContainer.addElement(this._gameView);this._contentContainer.addElement(this._creditsView);this._footerContainer=new ListContainerElement;this._footerContainer.setStyle("PercentWidth",100);this._footerContainer.setStyle("LayoutHorizontalAlign",
"right");this._poweredByContainerBackgroundShape=new RoundedRectangleShape;this._poweredByContainerBackgroundShape.setStyle("CornerRadiusTopLeft",5);this._poweredByContainer=new ListContainerElement;this._poweredByContainer.setStyle("LayoutGap",-1);this._poweredByContainer.setStyle("LayoutDirection","horizontal");this._poweredByContainer.setStyle("BackgroundColor","#777777");this._poweredByContainer.setStyle("Padding",2);this._poweredByContainer.setStyle("BackgroundShape",this._poweredByContainerBackgroundShape);
this._labelPoweredBy=new LabelElement;this._labelPoweredBy.setStyle("Text","Powered By ");this._labelPoweredBy.setStyle("TextColor","#000000");this._labelFlexCanvasJS=new LabelElement;this._labelFlexCanvasJS.setStyle("TextStyle","bold italic");this._labelFlexCanvasJS.setStyle("Text","FlexCanvasJS");this._labelFlexCanvasJS.setStyle("TextColor","#000000");this._poweredByContainer.addElement(this._labelPoweredBy);this._poweredByContainer.addElement(this._labelFlexCanvasJS);this._footerContainer.addElement(this._poweredByContainer);
this._rootContainer.addElement(this._contentContainer);this._rootContainer.addElement(this._footerContainer);this.addElement(this._rootContainer);var b=this;this._onButtonPlayClickInstance=function(a){b._onButtonPlayClick(a)};this._onButtonLowerLevelClickInstance=function(a){b._onButtonLowerLevelClick(a)};this._onButtonHigherLevelClickInstance=function(a){b._onButtonHigherLevelClick(a)};this._onPlayFieldQuitInstance=function(a){b._onPlayFieldQuit(a)};this._onLabelCreditsClickInstance=function(a){b._onLabelCreditsClick(a)};
this._onButtonCreditsDoneClickInstance=function(a){b._onButtonCreditsDoneClick(a)};this._buttonPlay.addEventListener("click",this._onButtonPlayClickInstance);this._buttonLowerLevel.addEventListener("click",this._onButtonLowerLevelClickInstance);this._buttonHigherLevel.addEventListener("click",this._onButtonHigherLevelClickInstance);this._playField.addEventListener("quit",this._onPlayFieldQuitInstance);this._labelCredits.addEventListener("click",this._onLabelCreditsClickInstance);this._buttonCreditsDone.addEventListener("click",
this._onButtonCreditsDoneClickInstance);for(var c,a=0;7>a;a++)for(c=0;41>c;c++)e=new TetriBlock,e.setStyle("Width",14),e.setStyle("Height",14),e.setStyle("X",13*c),e.setStyle("Y",13*a),this._titleContainer.addElement(e);var d=null,e,f;f=0;for(var g=1,h=TetriStackApplication.BlockColors.ORANGE,a=0;10>a;a++){d=TetriStackApplication.TitleLetterCoordinates["TETRISTACK"[a]];h==TetriStackApplication.BlockColors.ORANGE?h=TetriStackApplication.BlockColors.DARKBLUE:h==TetriStackApplication.BlockColors.DARKBLUE?
h=TetriStackApplication.BlockColors.GREEN:h==TetriStackApplication.BlockColors.GREEN?h=TetriStackApplication.BlockColors.YELLOW:h==TetriStackApplication.BlockColors.YELLOW?h=TetriStackApplication.BlockColors.LIGHTBLUE:h==TetriStackApplication.BlockColors.LIGHTBLUE?h=TetriStackApplication.BlockColors.RED:h==TetriStackApplication.BlockColors.RED?h=TetriStackApplication.BlockColors.PURPLE:h==TetriStackApplication.BlockColors.PURPLE&&(h=TetriStackApplication.BlockColors.ORANGE);for(c=0;c<d.length;c++)e=
g+d[c].x,f=1+d[c].y,f*=41,f+=e,e=this._titleContainer.getElementAt(f),e.setBlockColor(h);g+=4}}TetriStackApplication.prototype=Object.create(CanvasManager.prototype);TetriStackApplication.prototype.constructor=TetriStackApplication;TetriStackApplication.base=CanvasManager;
TetriStackApplication.prototype._onLabelCreditsClick=function(a){this._menuView.setStyle("Visible",!1);this._menuView.setStyle("IncludeInLayout",!1);this._creditsView.setStyle("Visible",!0);this._creditsView.setStyle("IncludeInLayout",!0)};TetriStackApplication.prototype._onButtonCreditsDoneClick=function(a){this._menuView.setStyle("Visible",!0);this._menuView.setStyle("IncludeInLayout",!0);this._creditsView.setStyle("Visible",!1);this._creditsView.setStyle("IncludeInLayout",!1)};
TetriStackApplication.prototype._onButtonPlayClick=function(a){this._menuView.setStyle("Visible",!1);this._menuView.setStyle("IncludeInLayout",!1);this._gameView.setStyle("Visible",!0);this._playField.startGame(Date.now())};TetriStackApplication.prototype._onPlayFieldQuit=function(a){this._menuView.setStyle("Visible",!0);this._menuView.setStyle("IncludeInLayout",!0);this._gameView.setStyle("Visible",!1)};
TetriStackApplication.prototype._onButtonLowerLevelClick=function(a){TetriStackApplication.StartAtLevel--;this._labelSelectedLevel.setStyle("Text",TetriStackApplication.StartAtLevel.toString());this._buttonHigherLevel.setStyle("Enabled",!0);1==TetriStackApplication.StartAtLevel?this._buttonLowerLevel.setStyle("Enabled",!1):this._buttonLowerLevel.setStyle("Enabled",!0)};
TetriStackApplication.prototype._onButtonHigherLevelClick=function(a){TetriStackApplication.StartAtLevel++;this._labelSelectedLevel.setStyle("Text",TetriStackApplication.StartAtLevel.toString());this._buttonLowerLevel.setStyle("Enabled",!0);10==TetriStackApplication.StartAtLevel?this._buttonHigherLevel.setStyle("Enabled",!1):this._buttonHigherLevel.setStyle("Enabled",!0)};TetriStackApplication.StartAtLevel=1;TetriStackApplication.MusicEnabled=!0;TetriStackApplication.SFXEnabled=!0;
TetriStackApplication.GlobalEventDispatcher=new EventDispatcher;
TetriStackApplication.TitleLetterCoordinates={T:[{x:0,y:0},{x:1,y:0},{x:2,y:0},{x:1,y:1},{x:1,y:2},{x:1,y:3},{x:1,y:4}],E:[{x:0,y:0},{x:1,y:0},{x:2,y:0},{x:0,y:1},{x:0,y:2},{x:1,y:2},{x:0,y:3},{x:0,y:4},{x:1,y:4},{x:2,y:4}],R:[{x:0,y:0},{x:1,y:0},{x:2,y:0},{x:0,y:1},{x:2,y:1},{x:0,y:2},{x:1,y:2},{x:0,y:3},{x:2,y:3},{x:0,y:4},{x:2,y:4}],I:[{x:0,y:0},{x:1,y:0},{x:2,y:0},{x:1,y:1},{x:1,y:2},{x:1,y:3},{x:0,y:4},{x:1,y:4},{x:2,y:4}],S:[{x:0,y:0},{x:1,y:0},{x:2,y:0},{x:0,y:1},{x:0,y:2},{x:1,y:2},{x:2,y:2},
{x:2,y:3},{x:0,y:4},{x:1,y:4},{x:2,y:4}],A:[{x:0,y:0},{x:1,y:0},{x:2,y:0},{x:0,y:1},{x:2,y:1},{x:0,y:2},{x:1,y:2},{x:2,y:2},{x:0,y:3},{x:2,y:3},{x:0,y:4},{x:2,y:4}],C:[{x:0,y:0},{x:1,y:0},{x:2,y:0},{x:0,y:1},{x:0,y:2},{x:0,y:3},{x:0,y:4},{x:1,y:4},{x:2,y:4}],K:[{x:0,y:0},{x:2,y:0},{x:0,y:1},{x:2,y:1},{x:0,y:2},{x:1,y:2},{x:0,y:3},{x:2,y:3},{x:0,y:4},{x:2,y:4}]};
TetriStackApplication.BlockColors={BLACK:{base:"#202020",lighter:CanvasElement.adjustColorLight("#202020",.03),darker:CanvasElement.adjustColorLight("#202020",-.08)},WHITE:{base:"#DDDDDD",lighter:CanvasElement.adjustColorLight("#DDDDDD",.12),darker:CanvasElement.adjustColorLight("#DDDDDD",-.12)},YELLOW:{base:"#BDBD00",lighter:CanvasElement.adjustColorLight("#BDBD00",.18),darker:CanvasElement.adjustColorLight("#BDBD00",-.06)},LIGHTBLUE:{base:"#3F8FFF",lighter:CanvasElement.adjustColorLight("#3F8FFF",
.12),darker:CanvasElement.adjustColorLight("#3F8FFF",-.12)},DARKBLUE:{base:"#0033CC",lighter:CanvasElement.adjustColorLight("#0033CC",.12),darker:CanvasElement.adjustColorLight("#0033CC",-.12)},ORANGE:{base:"#EA7A11",lighter:CanvasElement.adjustColorLight("#EA7A11",.16),darker:CanvasElement.adjustColorLight("#EA7A11",-.08)},PURPLE:{base:"#8928BC",lighter:CanvasElement.adjustColorLight("#8928BC",.12),darker:CanvasElement.adjustColorLight("#8928BC",-.12)},GREEN:{base:"#20B520",lighter:CanvasElement.adjustColorLight("#20B520",
.18),darker:CanvasElement.adjustColorLight("#20B520",-.08)},RED:{base:"#CC3333",lighter:CanvasElement.adjustColorLight("#CC3333",.12),darker:CanvasElement.adjustColorLight("#CC3333",-.12)}};
TetriStackApplication.GetBlockColor=function(a){return 0==a?TetriStackApplication.BlockColors.LIGHTBLUE:1==a?TetriStackApplication.BlockColors.YELLOW:2==a?TetriStackApplication.BlockColors.PURPLE:3==a?TetriStackApplication.BlockColors.GREEN:4==a?TetriStackApplication.BlockColors.RED:5==a?TetriStackApplication.BlockColors.DARKBLUE:6==a?TetriStackApplication.BlockColors.ORANGE:TetriStackApplication.BlockColors.BLACK};
TetriStackApplication.GetKickTable=function(a,b,c){var d=0;0!=a&&(d=1);for(a=0;a<TetriStackApplication.PieceRotateData[d].length;a++)if(TetriStackApplication.PieceRotateData[d][a].orientStart==b&&TetriStackApplication.PieceRotateData[d][a].orientEnd==c)return TetriStackApplication.PieceRotateData[d][a].kickTable;return[{x:0,y:0}]};TetriStackApplication.GetGenerationDelayTime=function(){return 200};TetriStackApplication.GetLockDelayTime=function(){return 500};
TetriStackApplication.GetFallSpeed=function(a){return 1E3*Math.pow(.8-.007*(a-1),a-1)};TetriStackApplication.GetBaseLinePoints=function(a){if(1==a)return 100;if(2==a)return 300;if(3==a)return 500;if(4==a)return 800};TetriStackApplication.GetBackToBackMultiplier=function(){return.5};
TetriStackApplication.PieceRotateData=[[{orientStart:0,orientEnd:1,kickTable:[{x:0,y:0},{x:-2,y:0},{x:1,y:0},{x:-2,y:1},{x:1,y:-2}]},{orientStart:1,orientEnd:0,kickTable:[{x:0,y:0},{x:2,y:0},{x:-1,y:0},{x:2,y:-1},{x:-1,y:2}]},{orientStart:1,orientEnd:2,kickTable:[{x:0,y:0},{x:-1,y:0},{x:2,y:0},{x:-1,y:-2},{x:2,y:1}]},{orientStart:2,orientEnd:1,kickTable:[{x:0,y:0},{x:1,y:0},{x:-2,y:0},{x:1,y:2},{x:-2,y:-1}]},{orientStart:2,orientEnd:3,kickTable:[{x:0,y:0},{x:2,y:0},{x:-1,y:0},{x:2,y:-1},{x:-1,y:2}]},
{orientStart:3,orientEnd:2,kickTable:[{x:0,y:0},{x:-2,y:0},{x:1,y:0},{x:-2,y:1},{x:1,y:-2}]},{orientStart:3,orientEnd:0,kickTable:[{x:0,y:0},{x:1,y:0},{x:-2,y:0},{x:1,y:2},{x:-2,y:-1}]},{orientStart:0,orientEnd:3,kickTable:[{x:0,y:0},{x:-1,y:0},{x:2,y:0},{x:-1,y:-2},{x:2,y:1}]}],[{orientStart:0,orientEnd:1,kickTable:[{x:0,y:0},{x:-1,y:0},{x:-1,y:-1},{x:0,y:2},{x:-1,y:2}]},{orientStart:1,orientEnd:0,kickTable:[{x:0,y:0},{x:1,y:0},{x:1,y:1},{x:0,y:-2},{x:1,y:-2}]},{orientStart:1,orientEnd:2,kickTable:[{x:0,
y:0},{x:1,y:0},{x:1,y:1},{x:0,y:-2},{x:1,y:-2}]},{orientStart:2,orientEnd:1,kickTable:[{x:0,y:0},{x:-1,y:0},{x:-1,y:-1},{x:0,y:2},{x:-1,y:2}]},{orientStart:2,orientEnd:3,kickTable:[{x:0,y:0},{x:1,y:0},{x:1,y:-1},{x:0,y:2},{x:1,y:2}]},{orientStart:3,orientEnd:2,kickTable:[{x:0,y:0},{x:-1,y:0},{x:-1,y:1},{x:0,y:-2},{x:-1,y:-2}]},{orientStart:3,orientEnd:0,kickTable:[{x:0,y:0},{x:-1,y:0},{x:-1,y:1},{x:0,y:-2},{x:-1,y:-2}]},{orientStart:0,orientEnd:3,kickTable:[{x:0,y:0},{x:1,y:0},{x:1,y:-1},{x:0,y:2},
{x:1,y:2}]}]];
TetriStackApplication.PieceData=[[[{x:0,y:1},{x:1,y:1},{x:2,y:1},{x:3,y:1}],[{x:2,y:0},{x:2,y:1},{x:2,y:2},{x:2,y:3}],[{x:0,y:2},{x:1,y:2},{x:2,y:2},{x:3,y:2}],[{x:1,y:0},{x:1,y:1},{x:1,y:2},{x:1,y:3}]],[[{x:0,y:0},{x:1,y:0},{x:0,y:1},{x:1,y:1}],[{x:0,y:0},{x:1,y:0},{x:0,y:1},{x:1,y:1}],[{x:0,y:0},{x:1,y:0},{x:0,y:1},{x:1,y:1}],[{x:0,y:0},{x:1,y:0},{x:0,y:1},{x:1,y:1}]],[[{x:1,y:0},{x:0,y:1},{x:1,y:1},{x:2,y:1}],[{x:1,y:0},{x:1,y:1},{x:2,y:1},{x:1,y:2}],[{x:0,y:1},{x:1,y:1},{x:2,y:1},{x:1,y:2}],[{x:1,
y:0},{x:0,y:1},{x:1,y:1},{x:1,y:2}]],[[{x:1,y:0},{x:2,y:0},{x:0,y:1},{x:1,y:1}],[{x:1,y:0},{x:1,y:1},{x:2,y:1},{x:2,y:2}],[{x:1,y:1},{x:2,y:1},{x:0,y:2},{x:1,y:2}],[{x:0,y:0},{x:0,y:1},{x:1,y:1},{x:1,y:2}]],[[{x:0,y:0},{x:1,y:0},{x:1,y:1},{x:2,y:1}],[{x:2,y:0},{x:1,y:1},{x:2,y:1},{x:1,y:2}],[{x:0,y:1},{x:1,y:1},{x:1,y:2},{x:2,y:2}],[{x:1,y:0},{x:0,y:1},{x:1,y:1},{x:0,y:2}]],[[{x:0,y:0},{x:0,y:1},{x:1,y:1},{x:2,y:1}],[{x:1,y:0},{x:2,y:0},{x:1,y:1},{x:1,y:2}],[{x:0,y:1},{x:1,y:1},{x:2,y:1},{x:2,y:2}],
[{x:1,y:0},{x:1,y:1},{x:0,y:2},{x:1,y:2}]],[[{x:2,y:0},{x:0,y:1},{x:1,y:1},{x:2,y:1}],[{x:1,y:0},{x:1,y:1},{x:1,y:2},{x:2,y:2}],[{x:0,y:1},{x:1,y:1},{x:2,y:1},{x:0,y:2}],[{x:0,y:0},{x:1,y:0},{x:1,y:1},{x:1,y:2}]]];
function TetriPlayField(){TetriPlayField.base.prototype.constructor.call(this);(new RoundedRectangleShape).setStyle("CornerRadius",5);this._gridRoundedBorder=new AnchorContainerElement;this._gridRoundedBorder.setStyle("Width",310);this._gridRoundedBorder.setStyle("Height",620);this._gridRoundedBorder.setStyleDefinitions(playFieldOuterContainerStyle);this._gridContainer=new AnchorContainerElement;this._gridContainer.setStyleDefinitions(playFieldInnerContainerStyle);this._gridContainerInner=new AnchorContainerElement;
this._gridContainerInner.setStyle("X",2);this._gridContainerInner.setStyle("Y",2);this._gridContainerInner.setStyle("Top",2);this._gridContainerInner.setStyle("Bottom",2);this._gameStartContainer=new ListContainerElement;this._gameStartContainer.setStyle("PercentWidth",100);this._gameStartContainer.setStyle("PercentHeight",100);this._gameStartContainer.setStyle("LayoutVerticalAlign","middle");this._gameStartContainer.setStyle("LayoutHorizontalAlign","center");this._gameStartContainer.setStyle("Visible",
!0);this._labelGameStartCount=new LabelElement;this._labelGameStartCount.setStyleDefinitions([labelPlayFieldStyle,labelPlayFieldStartCountSizeStyle]);this._gameStartContainer.addElement(this._labelGameStartCount);this._blockContainer=new AnchorContainerElement;this._blockContainer.setStyle("Width",300);this._blockContainer.setStyle("Height",690);this._blockContainer.setStyle("Bottom",0);this._blockContainer.setStyle("Visible",!1);this._menuPauseContainer=new ListContainerElement;this._menuPauseContainer.setStyle("PercentWidth",
100);this._menuPauseContainer.setStyle("PercentHeight",100);this._menuPauseContainer.setStyle("LayoutVerticalAlign","middle");this._menuPauseContainer.setStyle("LayoutHorizontalAlign","center");this._menuPauseContainer.setStyle("Visible",!1);this._labelMenuPauseTitle=new LabelElement;this._labelMenuPauseTitle.setStyle("Text","PAUSED");this._labelMenuPauseTitle.setStyleDefinitions([labelPlayFieldStyle,labelPlayFieldExLargeSizeStyle]);this._audioSelectContainerMenuPause=new TetriAudioSelectSettings;
this._audioSelectContainerMenuPause.setStyle("PaddingTop",50);this._audioSelectContainerMenuPause.setStyle("PaddingBottom",20);this._menuPauseButtonsContainer=new ListContainerElement;this._menuPauseButtonsContainer.setStyle("LayoutDirection","vertical");this._menuPauseButtonsContainer.setStyle("PaddingTop",50);this._menuPauseButtonsContainer.setStyle("LayoutGap",20);this._buttonMenuPauseResume=new ButtonElement;this._buttonMenuPauseResume.setStyle("Text","RESUME");this._buttonMenuPauseResume.setStyle("Width",
150);this._buttonMenuPauseResume.setStyle("PaddingTop",10);this._buttonMenuPauseResume.setStyle("PaddingBottom",10);this._buttonMenuPauseResume.setStyleDefinitions([buttonBackgroundStyle,buttonMenuStyle]);this._buttonMenuPauseQuit=new ButtonElement;this._buttonMenuPauseQuit.setStyle("Text","QUIT");this._buttonMenuPauseQuit.setStyle("Width",150);this._buttonMenuPauseQuit.setStyle("PaddingTop",10);this._buttonMenuPauseQuit.setStyle("PaddingBottom",10);this._buttonMenuPauseQuit.setStyleDefinitions([buttonBackgroundStyle,
buttonMenuStyle]);this._menuPauseButtonsContainer.addElement(this._buttonMenuPauseResume);this._menuPauseButtonsContainer.addElement(this._buttonMenuPauseQuit);this._menuPauseContainer.addElement(this._labelMenuPauseTitle);this._menuPauseContainer.addElement(this._audioSelectContainerMenuPause);this._menuPauseContainer.addElement(this._menuPauseButtonsContainer);this._menuGameOverContainer=new ListContainerElement;this._menuGameOverContainer.setStyle("PercentWidth",100);this._menuGameOverContainer.setStyle("PercentHeight",
100);this._menuGameOverContainer.setStyle("LayoutVerticalAlign","middle");this._menuGameOverContainer.setStyle("LayoutHorizontalAlign","center");this._menuGameOverContainer.setStyle("LayoutGap",20);this._menuGameOverContainer.setStyle("Visible",!1);this._labelMenuGameOverTitle=new LabelElement;this._labelMenuGameOverTitle.setStyle("Text","GAME OVER");this._labelMenuGameOverTitle.setStyleDefinitions([labelPlayFieldStyle,labelPlayFieldExLargeSizeStyle]);this._labelMenuGameOverScore=new LabelElement;
this._labelMenuGameOverScore.setStyle("Text","0");this._labelMenuGameOverScore.setStyleDefinitions([labelPlayFieldStyle,labelPlayFieldLargeSizeStyle]);this._audioSelectContainerGameOver=new TetriAudioSelectSettings;this._audioSelectContainerGameOver.setStyle("PaddingTop",50);this._audioSelectContainerGameOver.setStyle("PaddingBottom",20);this._menuGameOverButtonsContainer=new ListContainerElement;this._menuGameOverButtonsContainer.setStyle("LayoutDirection","vertical");this._menuGameOverButtonsContainer.setStyle("PaddingTop",
30);this._menuGameOverButtonsContainer.setStyle("LayoutGap",20);this._buttonMenuGameOverPlay=new ButtonElement;this._buttonMenuGameOverPlay.setStyle("Text","PLAY");this._buttonMenuGameOverPlay.setStyle("Width",150);this._buttonMenuGameOverPlay.setStyle("PaddingTop",10);this._buttonMenuGameOverPlay.setStyle("PaddingBottom",10);this._buttonMenuGameOverPlay.setStyleDefinitions([buttonBackgroundStyle,buttonMenuStyle]);this._buttonMenuGameOverQuit=new ButtonElement;this._buttonMenuGameOverQuit.setStyle("Text",
"QUIT");this._buttonMenuGameOverQuit.setStyle("Width",150);this._buttonMenuGameOverQuit.setStyle("PaddingTop",10);this._buttonMenuGameOverQuit.setStyle("PaddingBottom",10);this._buttonMenuGameOverQuit.setStyleDefinitions([buttonBackgroundStyle,buttonMenuStyle]);this._menuGameOverButtonsContainer.addElement(this._buttonMenuGameOverPlay);this._menuGameOverButtonsContainer.addElement(this._buttonMenuGameOverQuit);this._menuGameOverContainer.addElement(this._labelMenuGameOverTitle);this._menuGameOverContainer.addElement(this._labelMenuGameOverScore);
this._menuGameOverContainer.addElement(this._audioSelectContainerGameOver);this._menuGameOverContainer.addElement(this._menuGameOverButtonsContainer);this._gridContainerInner.addElement(this._gameStartContainer);this._gridContainerInner.addElement(this._blockContainer);this._gridContainerInner.addElement(this._menuPauseContainer);this._gridContainerInner.addElement(this._menuGameOverContainer);this._gridContainer.addElement(this._gridContainerInner);this._gridRoundedBorder.addElement(this._gridContainer);
this._nextRoundedBorder=new AnchorContainerElement;this._nextRoundedBorder.setStyle("X",315);this._nextRoundedBorder.setStyle("Width",140);this._nextRoundedBorder.setStyle("Height",120);this._nextRoundedBorder.setStyleDefinitions(playFieldOuterContainerStyle);this._nextContainer=new AnchorContainerElement;this._nextContainer.setStyleDefinitions(playFieldInnerContainerStyle);this._nextLabel=new LabelElement;this._nextLabel.setStyle("Text","Next");this._nextLabel.setStyleDefinitions([labelPlayFieldStyle,
labelPlayFieldLargeSizeStyle]);this._nextLabel.setStyle("Y",8);this._nextLabel.setStyle("HorizontalCenter",0);this._nextPieceContainer=new AnchorContainerElement;this._nextPieceContainer.setStyle("PercentWidth",100);this._nextPieceContainer.setStyle("Top",32);this._nextPieceContainer.setStyle("Bottom",3);this._nextPieceBlockContainer=new AnchorContainerElement;this._nextPieceBlockContainer.setStyle("HorizontalCenter",0);this._nextPieceBlockContainer.setStyle("VerticalCenter",0);this._nextPieceBlockContainer.setStyle("Visible",
!1);this._nextPieceContainer.addElement(this._nextPieceBlockContainer);this._nextContainer.addElement(this._nextLabel);this._nextContainer.addElement(this._nextPieceContainer);this._nextRoundedBorder.addElement(this._nextContainer);this._holdRoundedBorder=new AnchorContainerElement;this._holdRoundedBorder.setStyle("X",315);this._holdRoundedBorder.setStyle("Y",125);this._holdRoundedBorder.setStyle("Width",140);this._holdRoundedBorder.setStyle("Height",120);this._holdRoundedBorder.setStyleDefinitions(playFieldOuterContainerStyle);
this._holdContainer=new AnchorContainerElement;this._holdContainer.setStyleDefinitions(playFieldInnerContainerStyle);this._holdLabel=new LabelElement;this._holdLabel.setStyle("Text","Hold");this._holdLabel.setStyleDefinitions([labelPlayFieldStyle,labelPlayFieldLargeSizeStyle]);this._holdLabel.setStyle("Y",8);this._holdLabel.setStyle("HorizontalCenter",0);this._holdPieceContainer=new AnchorContainerElement;this._holdPieceContainer.setStyle("PercentWidth",100);this._holdPieceContainer.setStyle("Top",
32);this._holdPieceContainer.setStyle("Bottom",3);this._holdPieceBlockContainer=new AnchorContainerElement;this._holdPieceBlockContainer.setStyle("HorizontalCenter",0);this._holdPieceBlockContainer.setStyle("VerticalCenter",0);this._holdPieceBlockContainer.setStyle("Visible",!1);this._holdPieceContainer.addElement(this._holdPieceBlockContainer);this._holdContainer.addElement(this._holdLabel);this._holdContainer.addElement(this._holdPieceContainer);this._holdRoundedBorder.addElement(this._holdContainer);
this._scoreRoundedBorder=new AnchorContainerElement;this._scoreRoundedBorder.setStyle("X",315);this._scoreRoundedBorder.setStyle("Y",250);this._scoreRoundedBorder.setStyle("Width",140);this._scoreRoundedBorder.setStyle("Height",320);this._scoreRoundedBorder.setStyleDefinitions(playFieldOuterContainerStyle);this._scoreContainer=new ListContainerElement;this._scoreContainer.setStyleDefinitions(playFieldInnerContainerStyle);this._scoreContainer.setStyle("LayoutHorizontalAlign","center");this._scoreContainerSpacer0=
new CanvasElement;this._scoreContainerSpacer0.setStyle("PercentHeight",70);this._labelLevel=new LabelElement;this._labelLevel.setStyle("Text","Level");this._labelLevel.setStyleDefinitions([labelPlayFieldStyle,labelPlayFieldLargeSizeStyle]);this._labelLevelValue=new LabelElement;this._labelLevelValue.setStyle("Text","0");this._labelLevelValue.setStyleDefinitions([labelPlayFieldStyle,labelPlayFieldSmallSizeStyle]);this._labelLevelValue.setStyle("PaddingTop",8);this._scoreContainerSpacer1=new CanvasElement;
this._scoreContainerSpacer1.setStyle("PercentHeight",100);this._scoreContainerDivider1=new CanvasElement;this._scoreContainerDivider1.setStyleDefinitions(scoreControlsDividerStyle);this._scoreContainerSpacer2=new CanvasElement;this._scoreContainerSpacer2.setStyle("PercentHeight",100);this._labelLines=new LabelElement;this._labelLines.setStyle("Text","Lines");this._labelLines.setStyleDefinitions([labelPlayFieldStyle,labelPlayFieldLargeSizeStyle]);this._labelLineCount=new LabelElement;this._labelLineCount.setStyle("Text",
"0");this._labelLineCount.setStyleDefinitions([labelPlayFieldStyle,labelPlayFieldSmallSizeStyle]);this._labelLineCount.setStyle("PaddingTop",8);this._scoreContainerSpacer3=new CanvasElement;this._scoreContainerSpacer3.setStyle("PercentHeight",100);this._scoreContainerDivider2=new CanvasElement;this._scoreContainerDivider2.setStyleDefinitions(scoreControlsDividerStyle);this._scoreContainerSpacer4=new CanvasElement;this._scoreContainerSpacer4.setStyle("PercentHeight",100);this._labelScore=new LabelElement;
this._labelScore.setStyle("Text","Score");this._labelScore.setStyleDefinitions([labelPlayFieldStyle,labelPlayFieldLargeSizeStyle]);this._labelScoreValue=new LabelElement;this._labelScoreValue.setStyle("Text","0");this._labelScoreValue.setStyleDefinitions([labelPlayFieldStyle,labelPlayFieldSmallSizeStyle]);this._labelScoreValue.setStyle("PaddingTop",8);this._scoreContainerSpacer5=new CanvasElement;this._scoreContainerSpacer5.setStyle("PercentHeight",70);this._scoreContainer.addElement(this._scoreContainerSpacer0);
this._scoreContainer.addElement(this._labelLevel);this._scoreContainer.addElement(this._labelLevelValue);this._scoreContainer.addElement(this._scoreContainerSpacer1);this._scoreContainer.addElement(this._scoreContainerDivider1);this._scoreContainer.addElement(this._scoreContainerSpacer2);this._scoreContainer.addElement(this._labelLines);this._scoreContainer.addElement(this._labelLineCount);this._scoreContainer.addElement(this._scoreContainerSpacer3);this._scoreContainer.addElement(this._scoreContainerDivider2);
this._scoreContainer.addElement(this._scoreContainerSpacer4);this._scoreContainer.addElement(this._labelScore);this._scoreContainer.addElement(this._labelScoreValue);this._scoreContainer.addElement(this._scoreContainerSpacer5);this._scoreRoundedBorder.addElement(this._scoreContainer);this._menuButton=new ButtonElement;this._menuButton.setStyleDefinitions([buttonBackgroundStyle,buttonMenuStyle]);this._menuButton.setStyle("Width",140);this._menuButton.setStyle("Height",45);this._menuButton.setStyle("X",
315);this._menuButton.setStyle("Y",575);this.addElement(this._gridRoundedBorder);this.addElement(this._nextRoundedBorder);this.addElement(this._holdRoundedBorder);this.addElement(this._scoreRoundedBorder);this.addElement(this._menuButton);var a=this;this._onPlayFieldEnterFrameInstance=function(b){a._onPlayFieldEnterFrame(b)};this._onPlayFieldAddedInstance=function(b){b.getManager().addEventListener("keydown",a._onApplicationKeydownInstance);b.getManager().addEventListener("keyup",a._onApplicationKeyupInstance)};
this._onPlayFieldRemovedInstance=function(b){b.getManager().removeEventListener("keydown",a._onApplicationKeydownInstance);b.getManager().removeEventListener("keyup",a._onApplicationKeyupInstance)};this._onApplicationKeydownInstance=function(b){a._onApplicationKeydown(b)};this._onApplicationKeyupInstance=function(b){a._onApplicationKeyup(b)};this._onPlayFieldMenuClickInstance=function(b){a._onPlayFieldMenuClick(b)};this._onPlayFieldResumeClickInstance=function(b){a._onPlayFieldResumeClick(b)};this._onPlayFieldQuitClickInstance=
function(b){a._onPlayFieldQuitClick(b)};this._onPlayFieldNewGameInstance=function(b){a._onPlayFieldNewGame(b)};this.addEventListener("enterframe",this._onPlayFieldEnterFrameInstance);this.addEventListener("added",this._onPlayFieldAddedInstance);this.addEventListener("removed",this._onPlayFieldRemovedInstance);this._menuButton.addEventListener("click",this._onPlayFieldMenuClickInstance);this._buttonMenuPauseResume.addEventListener("click",this._onPlayFieldResumeClickInstance);this._buttonMenuPauseQuit.addEventListener("click",
this._onPlayFieldQuitClickInstance);this._buttonMenuGameOverQuit.addEventListener("click",this._onPlayFieldQuitClickInstance);this._buttonMenuGameOverPlay.addEventListener("click",this._onPlayFieldNewGameInstance);for(var b=0,c=0,d,b=0;23>b;b++)for(c=0;10>c;c++)d=new TetriBlock,d.setStyle("Width",30),d.setStyle("Height",30),d.setStyle("X",30*c),d.setStyle("Y",30*b),this._blockContainer.addElement(d);for(b=0;4>b;b++)d=new TetriBlock,d.setStyle("Width",25),d.setStyle("Height",25),this._nextPieceBlockContainer.addElement(d);
for(b=0;4>b;b++)d=new TetriBlock,d.setStyle("Width",25),d.setStyle("Height",25),this._holdPieceBlockContainer.addElement(d);this._paused=!0;this._pauseTime=-1;this._score=this._lines=this._level=0;this._levelUp=this._backToBackBonus=!1;this._generatePieceTime=this._lockRemaining=this._lockTime=this._fallTime=-1;this._lineClearPhase=null;this._linesClearTime=-1;this._gameStartPhase=null;this._gameStartCountTween=new Tween;this._gameStartCountTween.startVal=1;this._gameStartCountTween.endVal=0;this._gameStartCountTween.duration=
1E3;this._gameStartCountTween.easingFunction=Tween.easeOutSine;this._randomBag=[];this._currentBlocks=[];this._ghostBlocks=[];this._currentLines=[];this._currentPiece=null;this._currentOriginY=this._currentOriginX=this._currentOrient=0;this._currentResetLockY=-1;this._holdPiece=this._nextPiece=null;this._holdAvailable=!0;this._softDropTime=this._rightTime=this._leftTime=-1;this._holdKey=this._hardDropKey=this._rotateLeftKey=this._rotateRightKey=null;this._softDropKeys=[];this._leftRightKeys=[]}
TetriPlayField.prototype=Object.create(AnchorContainerElement.prototype);TetriPlayField.prototype.constructor=TetriPlayField;TetriPlayField.base=AnchorContainerElement;TetriPlayField.KeyholdDelay1=200;TetriPlayField.KeyholdDelay2=50;TetriPlayField.LineClearColumnTime=20;
TetriPlayField.prototype.startGame=function(a){this._paused=!1;this._setLevel(TetriStackApplication.StartAtLevel);this._gameStartPhase=3;this._labelGameStartCount.setStyle("Text",this._gameStartPhase.toString());this._labelGameStartCount.setStyle("Alpha",1);this._gameStartCountTween.startTime=a;1==TetriStackApplication.SFXEnabled&&sound_countdownbeep.play()};
TetriPlayField.prototype._onPlayFieldMenuClick=function(a){a=Date.now();this._paused=!0;this._pauseTime=a;this._menuButton.setStyle("Enabled",!1);this._menuPauseContainer.setStyle("Visible",!0);null==this._gameStartPhase&&sound_music.pause();this._blockContainer.setStyle("Visible",!1);this._gameStartContainer.setStyle("Visible",!1);this._nextPieceBlockContainer.setStyle("Visible",!1);this._holdPieceBlockContainer.setStyle("Visible",!1)};
TetriPlayField.prototype._onPlayFieldQuitClick=function(a){this._resetPlayField();this._dispatchEvent(new DispatcherEvent("quit"))};TetriPlayField.prototype._onPlayFieldNewGame=function(a){this._resetPlayField();this.startGame(Date.now())};
TetriPlayField.prototype._onPlayFieldResumeClick=function(a){a=Date.now();-1!=this._fallTime&&(this._fallTime+=a-this._pauseTime);-1!=this._lockTime&&(this._lockTime+=a-this._pauseTime);-1!=this._lineClearTime&&(this._lineClearTime+=a-this._pauseTime);null!=this._gameStartCountTween.startTime&&(this._gameStartCountTween.startTime+=a-this._pauseTime);-1!=this._generatePieceTime&&(this._generatePieceTime+=a-this._pauseTime);this._paused=!1;this._menuButton.setStyle("Enabled",!0);this._menuPauseContainer.setStyle("Visible",
!1);null==this._gameStartPhase?(this._blockContainer.setStyle("Visible",!0),1==TetriStackApplication.MusicEnabled&&sound_music.play()):this._gameStartContainer.setStyle("Visible",!0);null!=this._nextPiece&&this._nextPieceBlockContainer.setStyle("Visible",!0);null!=this._holdPiece&&this._holdPieceBlockContainer.setStyle("Visible",!0)};
TetriPlayField.prototype._gameOver=function(){this._paused=!0;this._currentPiece=null;this._menuButton.setStyle("Enabled",!1);this._gameStartContainer.setStyle("Visible",!1);this._menuPauseContainer.setStyle("Visible",!1);this._blockContainer.setStyle("Visible",!1);this._menuGameOverContainer.setStyle("Visible",!0);this._labelMenuGameOverScore.setStyle("Text",this._score.toString());sound_music.pause()};
TetriPlayField.prototype._resetPlayField=function(){for(var a,b=0;b<this._blockContainer.getNumElements();b++)a=this._blockContainer.getElementAt(b),a.setBlockColor(TetriStackApplication.BlockColors.BLACK),a.setIsGhost(!1);this._setLevel(0);this._lines=0;this._addToLines(0);this._score=0;this._addToScore(0);this._backToBackBonus=!1;this._lockRemaining=this._lockTime=this._fallTime=-1;this._lineClearPhase=null;this._linesClearTime=-1;this._levelUp=!1;this._generatePieceTime=-1;this._randomBag=[];this._currentBlocks=
[];this._ghostBlocks=[];this._currentLines=[];this._holdPiece=this._nextPiece=this._currentPiece=null;null==this._gameStartPhase;this._gameStartCountTween.startTime=null;this._paused=!0;this._menuButton.setStyle("Enabled",!0);this._gameStartContainer.setStyle("Visible",!0);this._menuPauseContainer.setStyle("Visible",!1);this._menuGameOverContainer.setStyle("Visible",!1);this._blockContainer.setStyle("Visible",!1);this._nextPieceBlockContainer.setStyle("Visible",!1);this._holdPieceBlockContainer.setStyle("Visible",
!1)};
TetriPlayField.prototype._onPlayFieldEnterFrame=function(a){if(1!=this._paused){a=Date.now();null!=this._currentPiece&&-1!=this._lockTime&&a>=this._lockTime&&(null!=this._testPosition(this._currentPiece,this._currentOrient,this._currentOriginX,this._currentOriginY+1)?(this._lockRemaining=0,this._lockTime=-1):this._lockCurrentPiece(this._lockTime));if(null!=this._currentPiece){for(;-1!=this._leftTime&&-1==this._rightTime&&a>=this._leftTime;)this._moveCurrentPiece(this._leftTime,"left"),this._leftTime+=TetriPlayField.KeyholdDelay2;
for(;-1!=this._rightTime&&-1==this._leftTime&&a>=this._rightTime;)this._moveCurrentPiece(this._rightTime,"right"),this._rightTime+=TetriPlayField.KeyholdDelay2;for(;-1!=this._softDropTime&&a>=this._softDropTime;)this._softDropTime+=Math.ceil(TetriStackApplication.GetFallSpeed(this._level)/20),1==this._moveCurrentPiece(this._softDropTime,"down")&&this._addToScore(1);for(;-1!=this._fallTime&&a>=this._fallTime;)this._moveCurrentPiece(this._fallTime,"down")}if(null!=this._lineClearPhase&&a>=this._linesClearTime){var b=
TetriStackApplication.BlockColors.BLACK,c=this._lineClearPhase-1;9<c&&(b=TetriStackApplication.BlockColors.WHITE,c-=10);if(-1==c)this._lineClearPhase=null,this._lineClearTime=-1,this._clearLines(),this._generatePiece(this._linesClearTime),1==this._levelUp&&(this._levelUp=!1,1==TetriStackApplication.SFXEnabled&&sound_levelUp.play());else{for(var d,e=0;e<this._currentLines.length;e++)d=this._getBlockAtGridPosition(c,this._currentLines[e]),d.setBlockColor(b);this._lineClearPhase--;this._linesClearTime+=
TetriPlayField.LineClearColumnTime}}-1!=this._generatePieceTime&&a>=this._generatePieceTime&&(this._generatePiece(this._generatePieceTime),this._generatePieceTime=-1);null!=this._gameStartPhase&&(b=this._gameStartCountTween.getValue(a),b==this._gameStartCountTween.endVal?(this._gameStartPhase--,1>this._gameStartPhase?(this._gameStartPhase=null,this._gameStartCountTween.startTime=null,this._nextPiece=this._getNextPiece(),this._generatePiece(a),this._gameStartContainer.setStyle("Visible",!1),this._blockContainer.setStyle("Visible",
!0),this._nextPieceBlockContainer.setStyle("Visible",!0),1==TetriStackApplication.MusicEnabled&&(sound_music.currentTime=0,sound_music.play())):(this._labelGameStartCount.setStyle("Text",this._gameStartPhase.toString()),this._labelGameStartCount.setStyle("Alpha",1),this._gameStartCountTween.startTime+=1E3,1==TetriStackApplication.SFXEnabled&&sound_countdownbeep.play())):this._labelGameStartCount.setStyle("Alpha",b))}};
TetriPlayField.prototype._lockCurrentPiece=function(a){var b=!0,c,d=[],e;for(c=0;c<this._currentBlocks.length;c++)e=this._getGridPositionFromBlock(this._currentBlocks[c]),-1==d.indexOf(e.y)&&d.push(e.y),2<e.y&&(b=!1);if(1==b)this._gameOver();else{var f;for(c=0;c<d.length;c++){e=!0;for(b=0;10>b;b++)if(f=this._getBlockAtGridPosition(b,d[c]),f.getBlockColor()==TetriStackApplication.BlockColors.BLACK){e=!1;break}1==e&&this._currentLines.push(d[c])}this._currentPiece=null;0<this._currentLines.length?(this._lineClearPhase=
20,this._linesClearTime=a+TetriPlayField.LineClearColumnTime,this._addToLines(this._currentLines.length),Math.floor(this._lines/10)+1>this._level&&(this._setLevel(Math.floor(this._lines/10)+1),this._levelUp=!0),a=TetriStackApplication.GetBaseLinePoints(this._currentLines.length)*this._level,4==this._currentLines.length?1==this._backToBackBonus?a+=Math.floor(.5*a):this._backToBackBonus=!0:this._backToBackBonus=!1,this._addToScore(a),1==TetriStackApplication.SFXEnabled&&(sound_lineComplete.currentTime=
0,sound_lineComplete.play())):this._generatePieceTime=a+TetriStackApplication.GetGenerationDelayTime()}};
TetriPlayField.prototype._clearLines=function(){var a=-1,b;for(b=0;b<this._currentLines.length;b++)this._currentLines[b]>a&&(a=this._currentLines[b]);var c,d,e,f=0;for(c=a;c>=-1*f;c--)if(0<=c&&-1<this._currentLines.indexOf(c))f++;else for(a=0;10>a;a++)d=0>b?null:this._getBlockAtGridPosition(a,c),e=this._getBlockAtGridPosition(a,c+f),null==d?e.setBlockColor(TetriStackApplication.BlockColors.BLACK):e.setBlockColor(d.getBlockColor());this._currentLines.splice(0,this._currentLines.length)};
TetriPlayField.prototype._generatePiece=function(a,b){1==b&&null!=this._holdPiece?this._currentPiece=this._holdPiece:(this._currentPiece=this._nextPiece,this._nextPiece=this._getNextPiece(),this._updateNextPiece());this._currentOrient=0;this._currentOriginX=3;this._currentOriginY=1;this._currentBlocks.splice(0,this._currentBlocks.length);this._lockTime=this._fallTime=this._currentResetLockY=-1;this._lockRemaining=TetriStackApplication.GetLockDelayTime();this._linesClearTime=-1;this._holdAvailable=
!0;1==this._currentPiece&&(this._currentOriginX=4);0==this._updatePosition(this._currentPiece,this._currentOrient,this._currentOriginX,this._currentOriginY)?this._gameOver():(this._moveCurrentPiece(a,"down"),this._updateGhost())};TetriPlayField.prototype._setLevel=function(a){this._level!=a&&(this._level=a,this._labelLevelValue.setStyle("Text",a.toString()))};TetriPlayField.prototype._addToScore=function(a){this._score+=a;this._labelScoreValue.setStyle("Text",this._score.toString())};
TetriPlayField.prototype._addToLines=function(a){this._lines+=a;this._labelLineCount.setStyle("Text",this._lines.toString())};TetriPlayField.prototype._updateNextPiece=function(){for(var a,b,c=TetriStackApplication.PieceData[this._nextPiece][0],d=TetriStackApplication.GetBlockColor(this._nextPiece),e=0;e<c.length;e++)a=this._nextPieceBlockContainer.getElementAt(e),b=c[e],a.setBlockColor(d),a.setStyle("X",25*b.x),0!=this._nextPiece?a.setStyle("Y",25*b.y):a.setStyle("Y",0)};
TetriPlayField.prototype._updateHoldPiece=function(){this._holdPieceBlockContainer.setStyle("Visible",!0);for(var a,b,c=TetriStackApplication.PieceData[this._holdPiece][0],d=TetriStackApplication.GetBlockColor(this._holdPiece),e=0;e<c.length;e++)a=this._holdPieceBlockContainer.getElementAt(e),b=c[e],a.setBlockColor(d),a.setStyle("X",25*b.x),0!=this._holdPiece?a.setStyle("Y",25*b.y):a.setStyle("Y",0)};
TetriPlayField.prototype._getNextPiece=function(){if(0==this._randomBag.length)for(var a=0;7>a;a++)this._randomBag.push(a);return this._randomBag.splice(Math.floor(Math.random()*(this._randomBag.length-1)),1)[0]};
TetriPlayField.prototype._moveCurrentPiece=function(a,b){if(null==this._currentPiece)return!1;var c=this._currentOriginX,d=this._currentOriginY;"left"==b?--c:"right"==b?c+=1:"down"==b&&(d+=1);result=this._updatePosition(this._currentPiece,this._currentOrient,c,d);"down"==b&&(this._fallTime=a+Math.ceil(TetriStackApplication.GetFallSpeed(this._level)),this._currentResetLockY<this._currentOriginY&&(this._currentResetLockY=this._currentOriginY,this._lockTime=-1,this._lockRemaining=TetriStackApplication.GetLockDelayTime()));
null==this._testPosition(this._currentPiece,this._currentOrient,this._currentOriginX,this._currentOriginY+1)?-1==this._lockTime&&(this._lockTime=a+this._lockRemaining):-1!=this._lockTime&&(this._lockRemaining=this._lockTime-a,this._lockTime=-1);1!=result||"right"!=b&&"left"!=b||this._updateGhost();return result};
TetriPlayField.prototype._rotateCurrentPiece=function(a,b){if(null!=this._currentPiece){newOrient="left"==a?this._currentOrient-1:this._currentOrient+1;0>newOrient&&(newOrient=3);3<newOrient&&(newOrient=0);for(var c=TetriStackApplication.GetKickTable(this._currentPiece,this._currentOrient,newOrient),d,e,f=!1,g=0;g<c.length;g++)if(d=this._currentOriginX+c[g].x,e=this._currentOriginY+c[g].y,1==this._updatePosition(this._currentPiece,newOrient,d,e)){f=!0;break}1==f&&(null==this._testPosition(this._currentPiece,
this._currentOrient,this._currentOriginX,this._currentOriginY+1)?-1==this._lockTime&&(this._lockTime=b+TetriStackApplication.GetLockDelayTime()):-1!=this._lockTime&&(this._lockRemaining=this._lockTime-b,this._lockTime=-1),this._updateGhost(),1==TetriStackApplication.SFXEnabled&&sound_rotate.play());return f}};
TetriPlayField.prototype._holdCurrentPiece=function(a){if(null!=this._currentPiece&&0!=this._holdAvailable){for(var b,c=0;c<this._currentBlocks.length;c++)b=this._currentBlocks[c],b.setBlockColor(TetriStackApplication.BlockColors.BLACK);b=this._currentPiece;this._generatePiece(a,!0);this._holdPiece=b;this._updateHoldPiece();this._holdAvailable=!1;1==TetriStackApplication.SFXEnabled&&sound_rotate.play()}};
TetriPlayField.prototype._hardDropCurrentPiece=function(a){if(null!=this._currentPiece){for(var b=this._currentOriginY+1,c;;){c=this._testPosition(this._currentPiece,this._currentOrient,this._currentOriginX,b);if(null==c){b--;break}b++}this._addToScore(2*(b-this._currentOriginY));this._updatePosition(this._currentPiece,this._currentOrient,this._currentOriginX,b);this._lockCurrentPiece(a)}};
TetriPlayField.prototype._onApplicationKeyup=function(a){a=a.getKeyCode();if(a==this._hardDropKey)this._hardDropKey=null;else if(a==this._rotateLeftKey)this._rotateLeftKey=null;else if(a==this._rotateRightKey)this._rotateRightKey=null;else if(a==this._holdKey)this._holdKey=null;else if(-1!=this._softDropKeys.indexOf(a))this._softDropKeys.splice(this._softDropKeys.indexOf(a),1),0==this._softDropKeys.length&&(this._softDropTime=-1);else if(-1!=this._leftRightKeys.indexOf(a))if(this._leftRightKeys.splice(this._leftRightKeys.indexOf(a),
1),0==this._leftRightKeys.length)this._rightTime=this._leftTime=-1;else{a=this._leftRightKeys[this._leftRightKeys.length-1];a=65==a||37==a||100==a?"left":"right";var b=Date.now();-1==this._leftTime&&"left"==a?(this._rightTime=-1,this._leftTime=b+TetriPlayField.KeyholdDelay1):-1==this._rightTime&&"right"==a&&(this._leftTime=-1,this._rightTime=b+TetriPlayField.KeyholdDelay1)}};
TetriPlayField.prototype._onApplicationKeydown=function(a){if(!(0<this._currentLines.length)){a=a.getKeyCode();var b=null;if(65==a||37==a||100==a)b="left";else if(68==a||39==a||102==a)b="right";else if(83==a||40==a||101==a)b="down";else if(87==a||38==a||104==a)b="up";else if(81==a||74==a||103==a)b="rleft";else if(69==a||76==a||105==a)b="rright";else if(32==a||75==a||96==a)b="hold";if(null!=b){var c=Date.now();"left"==b?-1==this._leftRightKeys.indexOf(a)&&(this._leftRightKeys.push(a),this._rightTime=
-1,-1==this._leftTime&&(this._leftTime=c+TetriPlayField.KeyholdDelay1,this._moveCurrentPiece(c,"left"))):"right"==b?-1==this._leftRightKeys.indexOf(a)&&(this._leftRightKeys.push(a),this._leftTime=-1,-1==this._rightTime&&(this._rightTime=c+TetriPlayField.KeyholdDelay1,this._moveCurrentPiece(c,"right"))):"down"==b?-1==this._softDropKeys.indexOf(a)&&(this._softDropKeys.push(a),1==this._softDropKeys.length&&(this._softDropTime=c+Math.ceil(TetriStackApplication.GetFallSpeed(this._level)/20),1==this._moveCurrentPiece(c,
"down")&&this._addToScore(1))):"up"==b?null==this._hardDropKey&&(this._hardDropKey=a,this._hardDropCurrentPiece(c)):"rleft"==b?null==this._rotateLeftKey&&(this._rotateLeftKey=a,this._rotateCurrentPiece("left",c)):"rright"==b?null==this._rotateRightKey&&(this._rotateRightKey=a,this._rotateCurrentPiece("right",c)):"hold"==b&&null==this._holdKey&&(this._holdKey=a,this._holdCurrentPiece(c))}}};
TetriPlayField.prototype._testPosition=function(a,b,c,d){var e,f,g=[];b=TetriStackApplication.PieceData[a][b];for(a=0;4>a;a++){e=c+b[a].x;f=d+b[a].y;if(0>e||9<e||0>f||22<f)return null;e=this._getBlockAtGridPosition(e,f);g.push(e)}for(a=0;a<g.length;a++)if(null==g[a]||g[a].getBlockColor()!=TetriStackApplication.BlockColors.BLACK&&0==g[a].getIsGhost()&&-1==this._currentBlocks.indexOf(g[a]))return null;return g};
TetriPlayField.prototype._getBlockAtGridPosition=function(a,b){return this._blockContainer.getElementAt(10*b+a)};TetriPlayField.prototype._getGridPositionFromBlock=function(a){var b=this._blockContainer.getElementIndex(a);if(null==a)return null;a={x:0,y:0};a.y=Math.floor(b/10);a.x=Math.floor(b%10);return a};
TetriPlayField.prototype._updateGhost=function(){var a;a=this._currentOriginY;for(var b=null,c;;)if(a++,c=this._testPosition(this._currentPiece,this._currentOrient,this._currentOriginX,a),null!=c)b=c;else break;if(null==b){for(a=0;a<this._ghostBlocks.length;a++)this._ghostBlocks[a].setIsGhost(!1),this._ghostBlocks[a].setBlockColor(TetriStackApplication.BlockColors.BLACK);this._ghostBlocks.splice(0,this._ghostBlocks.length)}else{c=TetriStackApplication.GetBlockColor(this._currentPiece);for(a=b.length-
1;0<=a;a--)-1<this._currentBlocks.indexOf(b[a])?b.splice(a,1):(b[a].setBlockColor(c),b[a].setIsGhost(!0));for(a=this._ghostBlocks.length-1;0<=a;a--)-1==b.indexOf(this._ghostBlocks[a])&&(this._ghostBlocks[a].setBlockColor(TetriStackApplication.BlockColors.BLACK),this._ghostBlocks[a].setIsGhost(!1));this._ghostBlocks=b}};
TetriPlayField.prototype._updatePosition=function(a,b,c,d){a=this._testPosition(a,b,c,d);if(null==a)return!1;var e;for(e=this._currentBlocks.length-1;0<=e;e--)-1==a.indexOf(this._currentBlocks[e])&&(this._currentBlocks[e].setBlockColor(TetriStackApplication.BlockColors.BLACK),this._currentBlocks[e].setIsGhost(!1));var f=TetriStackApplication.GetBlockColor(this._currentPiece),g;for(e=0;e<a.length;e++)a[e].setBlockColor(f),a[e].setIsGhost(!1),g=this._ghostBlocks.indexOf(a[e]),-1<g&&this._ghostBlocks.splice(g,
1);this._currentBlocks=a;this._currentOriginX=c;this._currentOriginY=d;this._currentOrient=b;return!0};function TetriBlock(){TetriBlock.base.prototype.constructor.call(this);this._isGhost=!1;this._blockColor=TetriStackApplication.BlockColors.BLACK}TetriBlock.prototype=Object.create(CanvasElement.prototype);TetriBlock.prototype.constructor=TetriBlock;TetriBlock.base=CanvasElement;TetriBlock.prototype.setBlockColor=function(a){this._blockColor!=a&&(this._blockColor=a,this._invalidateRender())};
TetriBlock.prototype.getBlockColor=function(){return this._blockColor};TetriBlock.prototype.setIsGhost=function(a){this._isGhost!=a&&(this._isGhost=a,this._invalidateRender())};TetriBlock.prototype.getIsGhost=function(){return this._isGhost};
TetriBlock.prototype._doRender=function(){var a=this._getGraphicsCtx(),b=0,c=0,d=this._width,e=this._height,f,g,h,l=null;if(1==this._isGhost){var k=TetriStackApplication.BlockColors.BLACK;f=k.base;g=k.lighter;h=k.darker;this._blockColor!=k&&(l=this._blockColor.base)}else f=this._blockColor.base,g=this._blockColor.lighter,h=this._blockColor.darker;a.beginPath();a.moveTo(b,c);a.lineTo(b+d,c);a.lineTo(b+d,c+e);a.lineTo(b,c+e);a.closePath();a.fillStyle=f;a.fill();c=b=.5;d=this._width-1;e=this._height-
1;a.beginPath();a.moveTo(b,c);a.lineTo(b+d,c);a.lineTo(b+d,c+e);a.lineTo(b,c+e);a.closePath();a.strokeStyle="#000000";a.stroke();c=b=1;d=this._width-2;e=this._height-2;f=Math.ceil(d/5);k=Math.ceil(e/5);a.beginPath();a.moveTo(b,c);a.lineTo(b+d,c);a.lineTo(b+d-f,c+k);a.lineTo(b+f,c+k);a.lineTo(b+f,c+e-k);a.lineTo(b,c+e);a.closePath();a.fillStyle=g;a.fill();a.beginPath();a.moveTo(b+d,c+e);a.lineTo(b,c+e);a.lineTo(b+f,c+e-k);a.lineTo(b+d-f,c+e-k);a.lineTo(b+d-f,c+k);a.lineTo(b+d,c);a.closePath();a.fillStyle=
h;a.fill();null!=l&&(c=b=1,d=this._width-2,e=this._height-2,a.beginPath(),a.moveTo(b,c),a.lineTo(b+d,c),a.lineTo(b+d,c+e),a.lineTo(b,c+e),a.closePath(),a.strokeStyle=l,a.stroke(),c=b=1.5,d=this._width-3,e=this._height-3,a.beginPath(),a.moveTo(b,c),a.lineTo(b+d,c),a.lineTo(b+d,c+e),a.lineTo(b,c+e),a.closePath(),a.strokeStyle=l,a.stroke())};
function TetriAudioSelectSettings(){TetriAudioSelectSettings.base.prototype.constructor.call(this);this.setStyle("LayoutDirection","horizontal");this._checkboxMusic=new CheckboxElement;this._checkboxMusic.setStyleDefinitions([labelSelectStyle,labelPlayFieldSmallSizeStyle,buttonBackgroundStyle]);this._checkboxMusic.setStyle("Text","Music");this._checkboxMusic.setSelected(TetriStackApplication.MusicEnabled);this._audioSelectContainerSpacer=new CanvasElement;this._audioSelectContainerSpacer.setStyle("Width",
50);this._checkboxSFX=new CheckboxElement;this._checkboxSFX.setStyleDefinitions([labelSelectStyle,labelPlayFieldSmallSizeStyle,buttonBackgroundStyle]);this._checkboxSFX.setStyle("Text","SFX");this._checkboxSFX.setSelected(TetriStackApplication.SFXEnabled);this.addElement(this._checkboxMusic);this.addElement(this._audioSelectContainerSpacer);this.addElement(this._checkboxSFX);var a=this;this._onCheckboxMusicChangedInstance=function(b){a._onCheckboxMusicChanged(b)};this._onCheckboxSFXChangedInstance=
function(b){a._onCheckboxSFXChanged(b)};this._onGlobalValueChangedInstance=function(b){a._onGlobalValueChanged(b)};this._onTetriAudioSelectSettingsAddedInstance=function(b){a._onTetriAudioSelectSettingsAdded(b)};this._onTetriAudioSelectSettingsRemovedInstance=function(b){a._onTetriAudioSelectSettingsRemoved(b)};this._checkboxMusic.addEventListener("changed",this._onCheckboxMusicChangedInstance);this._checkboxSFX.addEventListener("changed",this._onCheckboxSFXChangedInstance);this.addEventListener("added",
this._onTetriAudioSelectSettingsAddedInstance);this.addEventListener("removed",this._onTetriAudioSelectSettingsRemovedInstance)}TetriAudioSelectSettings.prototype=Object.create(ListContainerElement.prototype);TetriAudioSelectSettings.prototype.constructor=TetriAudioSelectSettings;TetriAudioSelectSettings.base=ListContainerElement;TetriAudioSelectSettings.prototype._onTetriAudioSelectSettingsAdded=function(a){TetriStackApplication.GlobalEventDispatcher.addEventListener("audiochanged",this._onGlobalValueChangedInstance)};
TetriAudioSelectSettings.prototype._onTetriAudioSelectSettingsRemoved=function(a){TetriStackApplication.GlobalEventDispatcher.removeEventListener("audiochanged",this._onGlobalValueChangedInstance)};TetriAudioSelectSettings.prototype._onCheckboxMusicChanged=function(a){TetriStackApplication.MusicEnabled=this._checkboxMusic.getSelected();TetriStackApplication.GlobalEventDispatcher._dispatchEvent(new DispatcherEvent("audiochanged"))};
TetriAudioSelectSettings.prototype._onCheckboxSFXChanged=function(a){TetriStackApplication.SFXEnabled=this._checkboxSFX.getSelected();TetriStackApplication.GlobalEventDispatcher._dispatchEvent(new DispatcherEvent("audiochanged"))};TetriAudioSelectSettings.prototype._onGlobalValueChanged=function(a){this._checkboxMusic.setSelected(TetriStackApplication.MusicEnabled);this._checkboxSFX.setSelected(TetriStackApplication.SFXEnabled)};
function CCAttributeLinks(){CCAttributeLinks.base.prototype.constructor.call(this);this.setStyle("LayoutDirection","horizontal");this.setStyle("LayoutVerticalAlign","middle");this._labelCreditSoundName=new LabelElement;this._labelCreditSoundName.setStyleDefinitions([textCreditsStyle,textLinkStyle]);this._labelCreditSoundBy=new LabelElement;this._labelCreditSoundBy.setStyleDefinitions([textCreditsStyle]);this._labelCreditSoundBy.setStyle("Text"," By ");this._labelCreditSoundAuthor=new LabelElement;
this._labelCreditSoundAuthor.setStyleDefinitions([textCreditsStyle,textLinkStyle]);this._labelCreditSoundSpace=new LabelElement;this._labelCreditSoundSpace.setStyleDefinitions([textCreditsStyle]);this._labelCreditSoundSpace.setStyle("Text"," ");this._labelCreditSoundLicense=new LabelElement;this._labelCreditSoundLicense.setStyleDefinitions([textCreditsStyle,textLinkStyle]);this.addElement(this._labelCreditSoundName);this.addElement(this._labelCreditSoundBy);this.addElement(this._labelCreditSoundAuthor);
this.addElement(this._labelCreditSoundSpace);this.addElement(this._labelCreditSoundLicense);var a=this;this._onLabelClickInstance=function(b){a._onLabelClick(b)};this._labelCreditSoundName.addEventListener("click",this._onLabelClickInstance);this._labelCreditSoundAuthor.addEventListener("click",this._onLabelClickInstance);this._labelCreditSoundLicense.addEventListener("click",this._onLabelClickInstance);this._licenseData=null}CCAttributeLinks.prototype=Object.create(ListContainerElement.prototype);
CCAttributeLinks.prototype.constructor=CCAttributeLinks;CCAttributeLinks.base=ListContainerElement;CCAttributeLinks.prototype.setLicenseData=function(a){this._licenseData=a;this._labelCreditSoundName.setStyle("Text",a.name);this._labelCreditSoundAuthor.setStyle("Text",a.author);this._labelCreditSoundLicense.setStyle("Text",a.license)};
CCAttributeLinks.prototype._onLabelClick=function(a){a=a.getTarget()==this._labelCreditSoundName?this._licenseData.link:a.getTarget()==this._labelCreditSoundAuthor?this._licenseData.authorLink:this._licenseData.licenseLink;window.open(a,"_blank"," ")};
